"""
Importador de lugares estáticos de New York City.
Moneda: USD.
"""
import sys, os
from datetime import date
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from db.database import init_db, get_or_create_city, insert_place

TODAY = date.today().isoformat()

PLACES = [

    # ── ICONOS / MONUMENTOS ───────────────────────────────────────────────────
    {
        "name": "Statue of Liberty & Ellis Island",
        "place_slug": "statue_liberty_nyc",
        "category": "Monumento / Patrimonio UNESCO / Historia",
        "description": "El símbolo más reconocido de Estados Unidos (1886, regalo de Francia). La estatua mide 93 metros desde el suelo hasta la antorcha. Visita incluye: Liberty Island (exterior gratis con ferry), pedestal (vistas desde 47 m), corona (vistas desde 94 m — reservar con meses de antelación). Ellis Island: el museo de la inmigración más importante del mundo — 12 millones de inmigrantes pasaron por aquí entre 1892 y 1954. Puedes buscar si tu familia pasó por Ellis Island en la base de datos online gratuita. Ferry sale de Battery Park (Manhattan) y Liberty State Park (NJ).",
        "opening_hours": "Ferries: 9:30-15:30h (última salida de regreso ~17:30h) | Estatua: 9-17h",
        "closed_days": "25 diciembre",
        "price": "Ferry + Liberty Island + Ellis Island: $24.50 adultos / $18.50 seniors / $14 niños (4-12) — ver statueoflibertytickets.com | Pedestal: $32 | Corona: $32 (reserva anticiapada)",
        "currency": "USD",
        "address": "Liberty Island & Ellis Island, New York Harbor, New York, NY (salida: Battery Park)",
        "contact": "nps.gov/stli | Tel: +1 212-363-3200",
        "official_website": "https://www.nps.gov/stli",
        "source": "https://www.nps.gov/stli",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Brooklyn Bridge",
        "place_slug": "brooklyn_bridge_nyc",
        "category": "Puente Histórico / Caminata / Icono",
        "description": "El puente más icónico de Nueva York (1883), una maravilla de ingeniería del siglo XIX. El paseo peatonal elevado sobre los carriles de tráfico tiene 1,3 km y da vistas espectaculares del skyline de Manhattan, el East River y el bajo Manhattan. Cruzar de Manhattan (City Hall Park) a Brooklyn (DUMBO) o viceversa a pie toma unos 30-40 min. Al llegar a Brooklyn: DUMBO (District Under the Manhattan Bridge Overpass) tiene la foto más famosa del puente desde Washington Street. Gratis y accesible 24h.",
        "opening_hours": "Siempre accesible (24h)",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "USD",
        "address": "Brooklyn Bridge, New York, NY (acceso Manhattan: Park Row / acceso Brooklyn: Adams St)",
        "contact": "nyc.gov",
        "official_website": "https://www.nyc.gov/html/dot/html/infrastructure/brooklyn-bridge.shtml",
        "source": "https://www.nyc.gov",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Empire State Building",
        "place_slug": "empire_state_nyc",
        "category": "Rascacielos / Observatorio / Icono Art Déco",
        "description": "El rascacielos más famoso del mundo (1931, art déco). 443 metros hasta la cima de la antena. Dos observatorios: planta 86 (320 m, terraza exterior con vistas de 360°) y planta 102 (443 m, cabina acristalada premium). La mejor vista del skyline de Manhattan incluyendo el Hudson, el East River, Central Park y los Cinco Distritos. De noche la iluminación del edificio cambia según eventos (Navidad, San Valentín, etc.). Las colas son legendarias — comprar entrada online con fecha y hora. Vista alternativa gratuita: desde el Top of the Rock del Rockefeller Center o desde la High Line.",
        "opening_hours": "Todos los días: 8-02h (último acceso 01:15h)",
        "closed_days": "Ninguno",
        "price": "Observatorio 86: $44 adultos / $38 seniors / $38 niños (6-12) — ver esbnyc.com | 102: $79 adicionales",
        "currency": "USD",
        "address": "20 W 34th St, Midtown Manhattan, New York, NY 10001",
        "contact": "esbnyc.com | Tel: +1 212-736-3100",
        "official_website": "https://www.esbnyc.com",
        "source": "https://www.esbnyc.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "One World Trade Center & 9/11 Memorial",
        "place_slug": "wtc_nyc",
        "category": "Memorial / Observatorio / Historia",
        "description": "El memorial de las Torres Gemelas: dos estanques cuadrados enormes donde estaban las torres, con los nombres de las 2.977 víctimas grabados en el bronce. El acceso al memorial exterior es gratuito. El Museo 9/11 (debajo del memorial) es poderoso y conmovedor — objetos recuperados, registros de audio, testimonios. One World Trade Center (541 m, el edificio más alto del hemisferio occidental) tiene el observatorio One World Observatory en los pisos 100-102 con la mejor vista de Nueva York desde el sur.",
        "opening_hours": "Memorial exterior: todos los días 7:30-21h | Museo: dom-jue 9-19h, vie-sáb 9-21h | One World Obs: 9-21h",
        "closed_days": "Ninguno (memorial exterior). Museo: Acción de Gracias, 25 dic",
        "price": "Memorial exterior: Gratuito | Museo 9/11: $33 adultos / $21 jóvenes (7-17) | One World Obs: $42 adultos — ver oneworldobservatory.com",
        "currency": "USD",
        "address": "180 Greenwich St, Lower Manhattan, New York, NY 10007",
        "contact": "911memorial.org | Tel: +1 212-266-5211",
        "official_website": "https://www.911memorial.org",
        "source": "https://www.911memorial.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Times Square",
        "place_slug": "times_square_nyc",
        "category": "Plaza / Noche / Entretenimiento / Broadway",
        "description": "El corazón del entretenimiento mundial: la intersección de Broadway y la 7ª Avenida en Midtown. 360.000 personas lo cruzan a diario. Pantallas LED de 8 pisos de altura, teatros de Broadway, restaurantes de cadena y el caos organizado más icónico del mundo. El Times Square New Year's Eve Ball Drop convoca a 1 millón de personas. De día es una experiencia pero de noche (especialmente entre 20-23h) es lo más parecido a vivir dentro de una película de Hollywood. Akshay importante: la mayoría de actividades son gratuitas (pasear). Broadway está a media cuadra.",
        "opening_hours": "Siempre accesible (24h)",
        "closed_days": "Ninguno",
        "price": "Gratuito (la plaza). Broadway: desde $50 a $500+",
        "currency": "USD",
        "address": "Broadway & 7th Ave, Midtown Manhattan, New York, NY 10036",
        "contact": "timessquarenyc.org",
        "official_website": "https://www.timessquarenyc.org",
        "source": "https://www.timessquarenyc.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Top of the Rock — Rockefeller Center",
        "place_slug": "top_rock_nyc",
        "category": "Observatorio / Arquitectura Art Déco / Midtown",
        "description": "El observatorio favorito de los neoyorquinos (mejor que el Empire State para muchos): tres terrazas en los pisos 67-70 del 30 Rockefeller Plaza. La diferencia clave con el Empire State: desde aquí se ve el Empire State dentro del skyline de Manhattan — la foto más icónica de la ciudad. También se ve Central Park al norte. El Rockefeller Center que lo rodea tiene 19 edificios art déco, la pista de hielo (en invierno) y el árbol de Navidad más famoso del mundo. NBC Studios está en el edificio — tours disponibles.",
        "opening_hours": "Todos los días: 9-23h (último ascenso 22:30h)",
        "closed_days": "Ninguno",
        "price": "$40 adultos / $38 seniors / $34 niños (6-12) — ver topoftherocknyc.com",
        "currency": "USD",
        "address": "30 Rockefeller Plaza, Midtown Manhattan, New York, NY 10112",
        "contact": "topoftherocknyc.com | Tel: +1 212-698-2000",
        "official_website": "https://www.topoftherocknyc.com",
        "source": "https://www.topoftherocknyc.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Grand Central Terminal",
        "place_slug": "grand_central_nyc",
        "category": "Estación Histórica / Arquitectura / Gastronomía",
        "description": "La estación de tren más bella del mundo (1913, Beaux-Arts). La sala principal (Main Concourse) con su techo verde azulado pintado con constelaciones y los rayos de luz que entran en diagonal es uno de los espacios arquitectónicos más fotografiados del planeta. 750.000 personas lo cruzan cada día. El susurro de la Whispering Gallery (debajo de la escalera del Oyster Bar): si te pones en una esquina de la bóveda y susurras, la persona en la esquina opuesta te escucha perfectamente. Grand Central Market (comida gourmet). Completamente gratuito visitar.",
        "opening_hours": "Todos los días: 5:30-02h",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "USD",
        "address": "89 E 42nd St, Midtown Manhattan, New York, NY 10017",
        "contact": "grandcentralterminal.com",
        "official_website": "https://www.grandcentralterminal.com",
        "source": "https://www.grandcentralterminal.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── PARQUES ────────────────────────────────────────────────────────────────
    {
        "name": "Central Park",
        "place_slug": "central_park_nyc",
        "category": "Parque / Pulmón Verde / Actividades",
        "description": "El parque más famoso del mundo (340 hectáreas en pleno Manhattan, 1858). 42 millones de visitas al año. Dentro del parque: el Lago (kayaks y rowboats de alquiler en Loeb Boathouse, $20/hora), el Great Lawn (conciertos gratuitos del Metropolitan Opera y NY Philharmonic en verano), Strawberry Fields (memorial a John Lennon frente al Dakota Building donde fue asesinado), el Conservatory Garden, el Belvedere Castle (gratis), el Zoo de Central Park ($14), la pista de patinaje Wollman Rink (invierno). Ciclismo, running, picnics, carreras de caballos en miniatura — todo el NYC real pasa por aquí.",
        "opening_hours": "Todos los días: 6-01h",
        "closed_days": "Ninguno",
        "price": "Gratuito (acceso) / Rowboat: $20/hora / Zoo: $14 adultos",
        "currency": "USD",
        "address": "Central Park, Manhattan, New York, NY (entre las calles 59 y 110)",
        "contact": "centralparknyc.org | Tel: +1 212-310-6600",
        "official_website": "https://www.centralparknyc.org",
        "source": "https://www.centralparknyc.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "The High Line",
        "place_slug": "high_line_nyc",
        "category": "Parque Elevado / Arte Urbano / Chelsea",
        "description": "Un parque lineal de 2,4 km construido sobre una vía de tren elevada en desuso (1934), convertida en parque público entre 2009 y 2014. Una de las transformaciones urbanas más exitosas del mundo. Vista del Hudson River, instalaciones de arte, jardines, amacas, puestos de comida. En verano: cine al aire libre, conciertos, mercados artesanales. El barrio de Chelsea debajo es el epicentro del arte contemporáneo de NY: más de 200 galerías de arte. Empieza en Gansevoort St (Meatpacking District) y termina en 34th St (Hudson Yards). Completamente gratuito.",
        "opening_hours": "Todos los días: 7-22h (jun-sep hasta 23h)",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "USD",
        "address": "The High Line, West Side Manhattan (Gansevoort St a 34th St), New York, NY",
        "contact": "thehighline.org | Tel: +1 212-500-6035",
        "official_website": "https://www.thehighline.org",
        "source": "https://www.thehighline.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Brooklyn Bridge Park",
        "place_slug": "brooklyn_bridge_park_nyc",
        "category": "Parque / Vistas de Manhattan / Brooklyn",
        "description": "El parque más nuevo y más fotogénico de NYC (2010-2018): 34 hectáreas en la ribera de Brooklyn con la mejor vista del skyline de Manhattan y el Brooklyn Bridge. Piers con actividades: kayak gratuito (Pier 2, verano), cancha de básquet, piscina de verano, pickleball, campos de fútbol. Smorgasburg (el mejor mercado de food vendors de NY) funciona los sábados de abril a octubre en el Pier 5. Jane's Carousel histórico ($3 el paseo). DUMBO al lado: el barrio más instagrameado del mundo con la foto de la calle bajo el puente.",
        "opening_hours": "Todos los días: 6-01h | Kayak gratuito: mayo-oct, vie-dom 9-17h",
        "closed_days": "Ninguno",
        "price": "Gratuito (acceso) / Jane's Carousel: $3",
        "currency": "USD",
        "address": "334 Furman St, Brooklyn, New York, NY 11201 (DUMBO / Brooklyn Heights)",
        "contact": "brooklynbridgepark.org | Tel: +1 718-222-9939",
        "official_website": "https://www.brooklynbridgepark.org",
        "source": "https://www.brooklynbridgepark.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },

    # ── MUSEOS ────────────────────────────────────────────────────────────────
    {
        "name": "The Metropolitan Museum of Art (The Met)",
        "place_slug": "met_nyc",
        "category": "Museo / Arte / El más grande de EEUU",
        "description": "El museo más grande de las Américas y uno de los cinco más importantes del mundo: 2 millones de objetos de todas las culturas y períodos históricos. Departamentos que impresionan: arte egipcio (el Templo de Dendur, 15 a.C., reconstruido íntegramente), armería medieval, impresionismo europeo, arte americano, moda (Costume Institute). La terraza del rooftop con vista de Central Park y el skyline de Manhattan es legendaria (solo en verano, incluida en entrada). El sistema de entrada 'pay what you wish' para residentes del estado de NY no aplica para turistas, pero $30 es muy razonable para la magnitud del museo.",
        "opening_hours": "Dom-jue: 10-17h | Vie-sáb: 10-21h",
        "closed_days": "Acción de Gracias, 25 diciembre, 1 enero, primer lunes de mayo",
        "price": "$30 adultos / $22 seniors (65+) / Gratuito menores 12 — ver metmuseum.org",
        "currency": "USD",
        "address": "1000 5th Ave, Upper East Side, New York, NY 10028",
        "contact": "metmuseum.org | Tel: +1 212-535-7710",
        "official_website": "https://www.metmuseum.org",
        "source": "https://www.metmuseum.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Museum of Modern Art (MoMA)",
        "place_slug": "moma_nyc",
        "category": "Museo / Arte Moderno y Contemporáneo",
        "description": "El museo de arte moderno más influyente del mundo (1929). Colección permanente: La noche estrellada de Van Gogh, Campbell's Soup Cans de Warhol, Les Demoiselles d'Avignon de Picasso, La persistencia de la memoria de Dalí, obras de Matisse, Mondrian, Pollock, Rothko, Cindy Sherman. El edificio renovado (2019, Diller Scofidio + Renfro) tiene galerías espectaculares. El jardín de esculturas al aire libre incluye bronces de Rodin y Giacometti. Los viernes por la tarde muchos neoyorquinos vienen porque la entrada es gratuita para los que ya tienen membresía — el ambiente es de lo más parisino de NYC.",
        "opening_hours": "Todos los días: 10:30-17:30h | Jue: 10:30-20h",
        "closed_days": "Acción de Gracias, 25 diciembre",
        "price": "$30 adultos / $22 seniors / $17 estudiantes / Gratuito menores 16 — ver moma.org",
        "currency": "USD",
        "address": "11 W 53rd St, Midtown Manhattan, New York, NY 10019",
        "contact": "moma.org | Tel: +1 212-708-9400",
        "official_website": "https://www.moma.org",
        "source": "https://www.moma.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "American Museum of Natural History (AMNH)",
        "place_slug": "amnh_nyc",
        "category": "Museo / Historia Natural / Ciencia / Familia",
        "description": "Uno de los mejores museos del mundo para familias con niños (y para todos): 45 salas permanentes con 33 millones de especímenes. Dinosaurios (la sala más popular del mundo para dinos: Tyrannosaurus Rex, Apatosaurus, Triceratops en tamaño real), ballena azul de 29 metros colgada del techo, Hall of Ocean Life, el Planetario Hayden (el más grande del hemisferio occidental). Las noches de jueves en el museo (hasta las 21h) son legendarias en NYC. Sistema 'suggested admission' — pueden pagar lo que quieran (mínimo técnicamente $0).",
        "opening_hours": "Todos los días: 10-17:30h | Jue: 10-21h",
        "closed_days": "Acción de Gracias",
        "price": "Suggested: $28 adultos / $16.50 niños (bajo 12) — ver amnh.org (se puede pagar menos)",
        "currency": "USD",
        "address": "200 Central Park West, Upper West Side, New York, NY 10024",
        "contact": "amnh.org | Tel: +1 212-769-5100",
        "official_website": "https://www.amnh.org",
        "source": "https://www.amnh.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "familias",
        "has_own_agenda": 1,
    },
    {
        "name": "Guggenheim Museum",
        "place_slug": "guggenheim_nyc",
        "category": "Museo / Arte / Arquitectura Icónica",
        "description": "El edificio más icónico de Frank Lloyd Wright (1959): una espiral de hormigón blanco que sube desde la planta baja hasta la cúpula de cristal. La colección incluye impresionismo, expresionismo y arte contemporáneo: Kandinsky (la mayor colección del mundo), Picasso, Chagall, Mondrian, Klee, Pollock. La experiencia de ver arte subiendo por la rampa espiral es única en el mundo. Los sábados de 17-20h la entrada es 'pay what you wish'. Ubicado en el Upper East Side frente a Central Park, cerca del Met.",
        "opening_hours": "Dom-mié y vie: 11-18h | Sáb: 11-20h",
        "closed_days": "Jueves, Acción de Gracias, 25 diciembre",
        "price": "$30 adultos / $18 estudiantes / Gratuito menores 12 / Sáb 17-20h: pay what you wish — ver guggenheim.org",
        "currency": "USD",
        "address": "1071 5th Ave, Upper East Side, New York, NY 10128",
        "contact": "guggenheim.org | Tel: +1 212-423-3500",
        "official_website": "https://www.guggenheim.org",
        "source": "https://www.guggenheim.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Brooklyn Museum",
        "place_slug": "brooklyn_museum_nyc",
        "category": "Museo / Arte / Brooklyn",
        "description": "El segundo museo más grande de NY (500.000 objetos) y uno de los mejores de EEUU. Colección egipcia excepcional, arte afroamericano y feminista (The Dinner Party de Judy Chicago), arte precolombino, moda. Primer sábado de cada mes: entrada gratuita y fiestas First Saturdays (desde las 17h: música en vivo, danza, arte). El musco más 'local' y menos turístico de NYC — atmosfera completamente diferente al Met. Prospect Park al lado (el Central Park de Brooklyn) es ideal para combinar.",
        "opening_hours": "Mié-dom: 11-18h | 1er sáb mes: 11-23h",
        "closed_days": "Lunes y martes, 1 enero, Acción de Gracias, 25 diciembre",
        "price": "$20 adultos / $16 seniors y estudiantes / Gratuito menores 19 y miembros / 1er sáb: gratuito desde 17h — ver brooklynmuseum.org",
        "currency": "USD",
        "address": "200 Eastern Pkwy, Crown Heights, Brooklyn, New York, NY 11238",
        "contact": "brooklynmuseum.org | Tel: +1 718-638-5000",
        "official_website": "https://www.brooklynmuseum.org",
        "source": "https://www.brooklynmuseum.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },

    # ── BARRIOS ────────────────────────────────────────────────────────────────
    {
        "name": "DUMBO y Brooklyn Heights",
        "place_slug": "dumbo_nyc",
        "category": "Barrio / Fotografía / Gastronomía / Arte",
        "description": "DUMBO (Down Under the Manhattan Bridge Overpass): el barrio más fotogénico de NYC. La foto desde Washington Street bajo el Manhattan Bridge con el Brooklyn Bridge al fondo es una de las más replicadas del mundo. Galerías de arte, estudios de artistas, restaurantes trendy, el Jane's Carousel histórico. Brooklyn Heights Promenade (5 min caminando): el paseo más elegante de Brooklyn con la mejor vista del skyline completo de Manhattan y el East River. Acceso desde el Brooklyn Bridge en 20 min a pie desde Manhattan.",
        "opening_hours": "Barrio: siempre | Brooklyn Heights Promenade: 6-24h",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "USD",
        "address": "Washington St / Front St, DUMBO, Brooklyn, New York, NY 11201",
        "contact": "dumbo.is",
        "official_website": "https://dumbo.is",
        "source": "https://dumbo.is",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Williamsburg — Brooklyn",
        "place_slug": "williamsburg_nyc",
        "category": "Barrio / Hipster / Gastronomía / Vida Nocturna",
        "description": "El barrio más hipster y creativo de NYC (y posiblemente del mundo). Bedford Avenue es la calle principal con tiendas vintage, cafés de especialidad, restaurantes de todas las cocinas del mundo y artistas callejeros. Smorgasburg en Marcy Ave los sábados (abr-oct): el mejor mercado de food vendors de NY con 100 stands de comida gourmet. La ribera del East River tiene vistas épicas del skyline de Manhattan. Por la noche: los mejores clubs independientes de NYC (Output cerró pero Nowadays y otros siguen). Acceso desde Manhattan: Metro L desde Union Square (14 min).",
        "opening_hours": "Barrio: siempre | Smorgasburg: sáb 11-18h (abr-oct)",
        "closed_days": "Smorgasburg solo sábados abr-oct",
        "price": "Gratuito (barrio) / Smorgasburg: comida desde $5",
        "currency": "USD",
        "address": "Bedford Ave / Metropolitan Ave, Williamsburg, Brooklyn, New York, NY 11211",
        "contact": "visitbrooklyn.org",
        "official_website": "https://www.visitbrooklyn.org",
        "source": "https://www.visitbrooklyn.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "adultos",
        "has_own_agenda": 0,
    },
    {
        "name": "Greenwich Village y West Village",
        "place_slug": "greenwich_village_nyc",
        "category": "Barrio / Bohemio / Jazz / Historia LGBTQIA+",
        "description": "El barrio bohemio histórico de Manhattan: el Jazz se inventó en los clubes de Bleecker Street en los años 50-60. Bob Dylan, Jimi Hendrix y Joni Mitchell empezaron aquí. Stonewall Inn (el bar donde comenzó el movimiento LGBTQIA+ en 1969 — hoy monumento nacional). West Village: las calles más bonitas y tranquilas de Manhattan con brownstones del siglo XIX y restaurantes íntimos. Washington Square Park: el parque más animado de Manhattan con músicos, ajedrecistas y estudiantes de la NYU. Los domingos en verano, conciertos gratuitos.",
        "opening_hours": "Barrio: siempre | Washington Square Park: 6-24h",
        "closed_days": "Ninguno",
        "price": "Gratuito (explorar)",
        "currency": "USD",
        "address": "Bleecker St / Christopher St, Greenwich Village, Manhattan, New York, NY 10014",
        "contact": "nyc.gov",
        "official_website": "https://www.nyc.gov",
        "source": "https://www.nyc.gov",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Harlem",
        "place_slug": "harlem_nyc",
        "category": "Barrio / Música / Historia Afroamericana / Gospel",
        "description": "El corazón cultural afroamericano de América. Apollo Theater (1934): donde arrancaron las carreras de Ella Fitzgerald, James Brown, Michael Jackson — Amateur Night los miércoles desde $22. Studio Museum in Harlem (arte afroamericano contemporáneo). Gospel Sunday: varias iglesias abren sus servicios dominicales a visitantes (Sunday morning entre 10-13h) — la experiencia musical más emotiva de NYC, completamente gratuita (donación voluntaria). La comida de soul food en los restaurantes de la calle 125 es legendaria. Barrio en profunda transformación — mezcla única de autenticidad y gentrificación.",
        "opening_hours": "Barrio: siempre | Apollo: según función | Gospel: dom 10-13h",
        "closed_days": "Ninguno",
        "price": "Gratuito (explorar) / Apollo desde $22 / Gospel: donación voluntaria",
        "currency": "USD",
        "address": "125th Street / Adam Clayton Powell Jr Blvd, Harlem, Manhattan, New York, NY 10027",
        "contact": "harlemnyc.com",
        "official_website": "https://www.harlemnyc.com",
        "source": "https://www.harlemnyc.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Chinatown y Little Italy",
        "place_slug": "chinatown_nyc",
        "category": "Barrio / Gastronomía / Cultura",
        "description": "El Chinatown de Manhattan es el más grande del hemisferio occidental: 100.000 residentes chinos en menos de 2 km². La comida más auténtica y barata de NYC: dim sum desde $3, pato laqueado, boba tea, puestos de frutas. Canal Street: mercados de imitaciones de bolsos de lujo (no compres — es ilegal pero existente). Little Italy (Mulberry Street) es hoy más un barrio italiano de nombre que de realidad — 4 cuadras de restaurantes turísticos con buena pasta. El barrio de Nolita (North of Little Italy) es el más chic con boutiques independientes.",
        "opening_hours": "Barrio: siempre | Restaurantes de dim sum: 9-15h (mejor 10-13h)",
        "closed_days": "Ninguno",
        "price": "Gratuito (explorar) / Dim sum desde $3",
        "currency": "USD",
        "address": "Canal St / Mott St, Chinatown / Little Italy, Manhattan, New York, NY 10013",
        "contact": "explorechinatown.com",
        "official_website": "https://www.explorechinatown.com",
        "source": "https://www.explorechinatown.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── GASTRONOMÍA / MERCADOS ─────────────────────────────────────────────────
    {
        "name": "Chelsea Market",
        "place_slug": "chelsea_market_nyc",
        "category": "Mercado Gourmet / Gastronomía / Arquitectura Industrial",
        "description": "El mercado gastronómico más popular de NYC, en el edificio histórico de la fábrica de galletas Nabisco (1890s), donde se inventó la Oreo en 1912. Hoy: 35 vendors con lo mejor de la cocina de NYC — mariscos, lobster rolls, comida italiana, panadería artesanal, The Lobster Place (el mejor marisco crudo de Manhattan). El edificio industrial con las chimeneas y las tuberías a la vista es fotogénico. La High Line comienza a una cuadra. El barrio de Chelsea que lo rodea es el más importante del mundo en galerías de arte contemporáneo.",
        "opening_hours": "Lun-sáb: 7-21h | Dom: 8-21h",
        "closed_days": "Acción de Gracias, 25 diciembre",
        "price": "Gratuito (entrar) / Comida desde $8",
        "currency": "USD",
        "address": "75 9th Ave, Chelsea, Manhattan, New York, NY 10011",
        "contact": "chelseamarket.com | Tel: +1 212-652-2110",
        "official_website": "https://www.chelseamarket.com",
        "source": "https://www.chelseamarket.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Smorgasburg",
        "place_slug": "smorgasburg_nyc",
        "category": "Mercado de Comida / Weekends / Brooklyn",
        "description": "El mayor mercado al aire libre de food vendors de EEUU (fundado 2011). 100 pequeños productores y chefs con sus platos más creativos. Se inventó aquí el ramen burger, el cronut de ramen y decenas de otras tendencias foodie. Sábados en Prospect Park, Brooklyn (primavera-otoño). Domingo en el Lower East Side (Manhattan). La comida es cara para lo que es ($14-20 por plato) pero la variedad y creatividad es única en el mundo. Llegar entre 11-13h antes de que se acabe lo más popular.",
        "opening_hours": "Sáb: 11-18h en Prospect Park (abr-oct) | Dom: 11-18h en LES (abr-oct)",
        "closed_days": "Nov-mar y días de lluvia extrema",
        "price": "Gratuito (entrar) / Platos $10-20",
        "currency": "USD",
        "address": "Saturdays: Breeze Hill, Prospect Park, Brooklyn, NY | Sundays: Seward Park, LES Manhattan",
        "contact": "smorgasburg.com",
        "official_website": "https://www.smorgasburg.com",
        "source": "https://www.smorgasburg.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── ESPECTÁCULOS / ENTRETENIMIENTO ─────────────────────────────────────────
    {
        "name": "Broadway — Distrito de Teatros",
        "place_slug": "broadway_nyc",
        "category": "Teatro / Musical / Entretenimiento",
        "description": "El teatro profesional más importante del mundo: 41 teatros con capacidad de más de 500 butacas entre las calles 40 y 54 en Midtown. Siempre hay entre 30 y 40 musicales y obras corriendo simultáneamente: The Lion King, Wicked, Hamilton, Chicago, MJ The Musical, y docenas más. TKTS: la caseta en Times Square (7 días, desde 15h) y en el South Street Seaport vende entradas con descuentos del 20-50% el mismo día. Rush tickets y lotteries online para entradas desde $30-50 para los shows más populares. Off-Broadway y Off-Off-Broadway: alternativas de alta calidad desde $15.",
        "opening_hours": "Shows: generalmente mar-dom a las 19 o 19:30h | Mat: mié, sáb y dom 14h | TKTS: lun-sáb 15-20h, dom 11-19h",
        "closed_days": "Lunes (la mayoría de shows)",
        "price": "Desde $30 (lottery/rush) a $500+ (front row Hamilton) | TKTS descuentos 20-50% — ver broadwaydirect.com",
        "currency": "USD",
        "address": "Theater District: W 40th to W 54th St, 7th to 9th Ave, Midtown Manhattan, New York, NY",
        "contact": "broadwaydirect.com | tdf.org (TKTS)",
        "official_website": "https://www.broadwaydirect.com",
        "source": "https://www.broadwaydirect.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Lincoln Center for the Performing Arts",
        "place_slug": "lincoln_center_nyc",
        "category": "Centro de Artes Escénicas / Ópera / Ballet / Música",
        "description": "El complejo de artes escénicas más importante del mundo: 12 instituciones incluyendo el Metropolitan Opera, la New York Philharmonic, el New York City Ballet, la Juilliard School y el Film Society of Lincoln Center. 11 salas de espectáculos en 6 hectáreas. En verano: Mostly Mozart Festival (conciertos al aire libre, algunos gratuitos), Out of Doors (festivales gratuitos en la explanada). El Metropolitan Opera tiene los Opera HD Transmissions en cines de todo el mundo. La plaza central frente al Lincoln Center es de las más elegantes de NYC.",
        "opening_hours": "Taquillas: lun-sáb 10-18h | Espectáculos: según calendario",
        "closed_days": "Variable",
        "price": "MET Opera: desde $25 (Family Circle) a $400+ | NY Philharmonic: desde $30 | Eventos gratuitos en verano — ver lincolncenter.org",
        "currency": "USD",
        "address": "10 Lincoln Center Plaza, Upper West Side, Manhattan, New York, NY 10023",
        "contact": "lincolncenter.org | Tel: +1 212-875-5456",
        "official_website": "https://www.lincolncenter.org",
        "source": "https://www.lincolncenter.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },

    # ── DEPORTES ──────────────────────────────────────────────────────────────
    {
        "name": "Yankee Stadium",
        "place_slug": "yankee_stadium_nyc",
        "category": "Béisbol / MLB / Turismo Deportivo",
        "description": "El estadio del equipo de béisbol más famoso del mundo: los New York Yankees (27 títulos de World Series). El nuevo Yankee Stadium (2009) tiene capacidad para 47.309 personas. Tours del estadio incluyendo Monument Park (monolitos y placas de los jugadores más importantes de la historia: Ruth, DiMaggio, Mantle, Jeter). La temporada regular de MLB va de abril a septiembre, playoffs en octubre. Ir a un partido de béisbol en el Bronx es una de las experiencias más americanas posibles: hot dogs, cervezas y 'Take Me Out to the Ball Game' en el 7mo inning.",
        "opening_hours": "Tours: lun-sáb 10-17h (según disponibilidad y partidos) | Partidos: según calendar.mlb.com",
        "closed_days": "Variable según partido",
        "price": "Tour: $30 adultos / $25 seniors y niños | Entradas partidos: desde $15 (bleachers) a $300+ — ver mlb.com/yankees",
        "currency": "USD",
        "address": "1 E 161st St, The Bronx, New York, NY 10451",
        "contact": "mlb.com/yankees | Tel: +1 718-293-4300",
        "official_website": "https://www.mlb.com/yankees",
        "source": "https://www.mlb.com/yankees",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Citi Field — New York Mets",
        "place_slug": "citi_field_nyc",
        "category": "Béisbol / MLB / Queens",
        "description": "El estadio de los New York Mets (2009), en el barrio de Queens junto al Flushing Meadows. Capacidad 41.922 personas. El ambiente es más familiar y accesible que el Yankee Stadium, y los precios de las entradas son más razonables. El vecindario de Flushing (Queens) donde está el estadio tiene el mejor Chinatown de NYC fuera de Manhattan — dim sum extraordinario antes del partido. Flushing Meadows Park (donde estuvieron las ferias mundiales de 1939 y 1964) tiene el Unisphere (globo de acero de 43 metros, símbolo del puente entre culturas).",
        "opening_hours": "Partidos: según calendar.mlb.com | Tours: lun-sáb 10-16h (días sin partido)",
        "closed_days": "Lunes fuera de temporada",
        "price": "Entradas desde $20 (Promenade Reserved) a $200+ — ver mlb.com/mets",
        "currency": "USD",
        "address": "41 Seaver Way, Flushing, Queens, New York, NY 11368",
        "contact": "mlb.com/mets | Tel: +1 718-507-6387",
        "official_website": "https://www.mlb.com/mets",
        "source": "https://www.mlb.com/mets",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Madison Square Garden",
        "place_slug": "msg_nyc",
        "category": "Arena / Deportes / Conciertos / NYC",
        "description": "El escenario de eventos más famoso del mundo: 'The World's Most Famous Arena'. Casa de los New York Knicks (NBA) y los New York Rangers (NHL). Conciertos legendarios de todos los artistas top del mundo. Billy Joel ha dado más de 150 shows aquí (récord). La Cuarta Avenida de Madison Square Garden es la más densa en eventos del mundo — siempre hay algo. La arena tiene 20.000 asientos y está construida encima de Penn Station (la estación de tren más concurrida de América).",
        "opening_hours": "Según evento | Taquilla: lun-sáb 11-18h",
        "closed_days": "Variable según evento",
        "price": "Knicks NBA: desde $45 | Rangers NHL: desde $50 | Conciertos: según artista — ver msg.com",
        "currency": "USD",
        "address": "4 Pennsylvania Plaza, Midtown Manhattan, New York, NY 10001 (encima de Penn Station)",
        "contact": "msg.com | Tel: +1 212-465-6741",
        "official_website": "https://www.msg.com",
        "source": "https://www.msg.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
]


def import_static_places_nyc():
    print(f"\nImportando {len(PLACES)} lugares estáticos de New York City...")
    init_db()
    city_id = get_or_create_city("New York City", "United States")

    for place in PLACES:
        insert_place(city_id, place)

    print(f"\nImportacion completada: {len(PLACES)} lugares de New York City")


if __name__ == "__main__":
    import_static_places_nyc()
