"""
Importador de lugares estáticos de Santiago de Chile.
Cubre venues imprescindibles sin API pública de eventos.
Idiosincrasia chilena: fútbol (Superclásico), vino, ski en los Andes, Neruda, Mercado Central.
"""
import sys, os
from datetime import date
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from db.database import init_db, get_or_create_city, insert_place

TODAY = date.today().isoformat()

PLACES = [
    # ── HISTORIA / PATRIMONIO ─────────────────────────────────────────────────
    {
        "name": "Palacio de La Moneda",
        "place_slug": "la_moneda_scl",
        "category": "Monumento / Histórico",
        "description": "Sede del Gobierno de Chile y símbolo histórico nacional. Construcción neoclásica del siglo XVIII (1805). Escenario del golpe de Estado del 11 de septiembre de 1973. Visitas guiadas al patio interior. El Centro Cultural La Moneda (CCLM) está en el subterráneo.",
        "opening_hours": "Patio exterior: lun a vie 10 a 18 h | Visitas guiadas: consultar palaciolamoneda.gob.cl",
        "closed_days": "Fines de semana (solo exterior libre acceso)",
        "price": "Gratuito (patio exterior) / Ver ccplm.cl para exposiciones del CCLM",
        "currency": "CLP",
        "address": "Plaza de la Constitución s/n, Santiago Centro",
        "contact": "palaciolamoneda.gob.cl",
        "official_website": "https://www.palaciolamoneda.gob.cl",
        "source": "https://www.palaciolamoneda.gob.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },
    {
        "name": "Plaza de Armas de Santiago",
        "place_slug": "plaza_de_armas_scl",
        "category": "Plaza Histórica / Espacio Público",
        "description": "El corazón histórico de Santiago, fundada en 1541 por Pedro de Valdivia. Rodeada de la Catedral Metropolitana (entrada gratuita), el Correo Central (arquitectura art nouveau, visitable), el Museo Histórico Nacional (gratuito) y la Real Audiencia. De día: ajedrecistas que juegan partidas contra cualquier visitante, artistas callejeros, feriantes y palomas. A metros: el Portal Fernández Concha, el Paseo Ahumada peatonal y el Barrio Financiero. Punto de partida ideal para recorrer el centro histórico a pie.",
        "opening_hours": "Siempre accesible",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "CLP",
        "address": "Plaza de Armas, Santiago Centro",
        "contact": "turismosantiago.cl",
        "official_website": "https://www.santiago.cl",
        "source": "https://www.santiago.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Cerro Santa Lucía",
        "place_slug": "cerro_santa_lucia_scl",
        "category": "Parque / Histórico",
        "description": "Colina histórica donde Pedro de Valdivia fundó Santiago en 1541. Jardines en terrazas, fuentes de agua, la Terraza Caupolicán y vistas panorámicas del centro. Entrada libre, imprescindible.",
        "opening_hours": "Todos los días: 9 a 21 h",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "CLP",
        "address": "Av. Libertador Bernardo O'Higgins 499, Santiago Centro",
        "contact": "santiago.cl",
        "official_website": "https://www.santiago.cl",
        "source": "https://www.santiago.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Cementerio General de Santiago",
        "place_slug": "cementerio_general_scl",
        "category": "Patrimonio / Histórico",
        "description": "Uno de los cementerios más grandes e históricos de Latinoamérica. Mausoleos de presidentes, artistas y figuras históricas. Arquitectura neoclásica y Monumento Nacional. Similar al Cementerio de Recoleta en Buenos Aires.",
        "opening_hours": "Todos los días: 8 a 18 h",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "CLP",
        "address": "Av. Profesor Zañartu 951, Recoleta, Santiago",
        "contact": "cementeriogeneral.cl",
        "official_website": "https://www.cementeriogeneral.cl",
        "source": "https://www.cementeriogeneral.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── NATURALEZA / PANORAMAS ────────────────────────────────────────────────
    {
        "name": "Cerro San Cristóbal (Parque Metropolitano)",
        "place_slug": "cerro_san_cristobal_scl",
        "category": "Parque / Naturaleza",
        "description": "El pulmón verde de Santiago: 722 hectáreas con la estatua de la Virgen en la cumbre (880 msnm). Funicular histórico de 1925 (sube desde Bellavista hasta la cumbre en 10 min, $3.000 CLP adultos). Teleférico entre la cumbre y Providencia ($5.000 CLP). Zoológico Metropolitano. Jardín Japonés (gratuito mar y mié). Piscinas temperadas (temporada verano). Senderos para trekking y running. Bicicletería dentro del parque con alquiler por hora. Vistas panorámicas de 360° de la ciudad y la Cordillera nevada. Acceso peatonal libre por Pío Nono (Bellavista) o Pedro de Valdivia (Providencia).",
        "opening_hours": "Parque: todos los días 8:30 a 20 h | Funicular: mar a dom 10 a 18:45 h | Teleférico: mar a dom 10 a 18:30 h | Zoológico: mar a dom 10 a 18 h",
        "closed_days": "Funicular y teleférico cerrados los lunes",
        "price": "Parque gratuito / Funicular: $3.000 CLP adultos, $1.500 CLP niños / Teleférico: $5.000 CLP / Zoológico: $4.500 CLP adultos, $2.200 CLP niños / Bicicletas: desde $2.000 CLP la hora - ver parquemet.cl",
        "currency": "CLP",
        "address": "Pío Nono 450, Bellavista, Santiago",
        "contact": "parquemet.cl | Tel: +56 2 2730-1300",
        "official_website": "https://www.parquemet.cl",
        "source": "https://www.parquemet.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Sky Costanera (Gran Torre Santiago)",
        "place_slug": "sky_costanera_scl",
        "category": "Mirador / Atracción",
        "description": "El mirador más alto de América Latina (300 metros, pisos 61-62). Vistas de 360° de Santiago, la Cordillera de los Andes y en días despejados hasta el Pacífico. Dentro del Mall Costanera Center en Providencia.",
        "opening_hours": "Lun a jue: 10 a 21 h | Vie a dom: 10 a 21:30 h",
        "closed_days": "Ninguno",
        "price": "Desde $14.000 CLP adultos / $10.000 CLP niños (3-12 años) - ver skycostanera.cl",
        "currency": "CLP",
        "address": "Av. Andrés Bello 2425, Providencia, Santiago",
        "contact": "skycostanera.cl | Tel: +56 2 2916-9269",
        "official_website": "https://www.skycostanera.cl",
        "source": "https://www.skycostanera.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── MERCADOS / BARRIOS ICÓNICOS ───────────────────────────────────────────
    {
        "name": "Mercado Central de Santiago",
        "place_slug": "mercado_central_scl",
        "category": "Mercado / Gastronomía",
        "description": "El mercado de pescados y mariscos más famoso de Chile. Construcción de hierro del siglo XIX (1872), Monumento Nacional. Ideal para comer congrio, reineta y locos frescos. Gastronomía identitaria chilena imprescindible.",
        "opening_hours": "Todos los días: 6 a 20 h (restaurantes hasta 17 h aprox.)",
        "closed_days": "Ninguno",
        "price": "Gratuito (acceso libre) / Almuerzo desde $8.000 a $15.000 CLP",
        "currency": "CLP",
        "address": "San Pablo 967, Santiago Centro",
        "contact": "mercadocentral.cl",
        "official_website": "https://www.mercadocentral.cl",
        "source": "https://www.mercadocentral.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "La Vega Central",
        "place_slug": "la_vega_central_scl",
        "category": "Mercado / Gastronomía",
        "description": "El mercado popular más grande y auténtico de Santiago. Frutas, verduras, hierbas y especias a precios de feria. A dos cuadras del Mercado Central. Ideal para vivir la vida cotidiana santiaguina.",
        "opening_hours": "Lun a sab: 6 a 17 h | Dom: 6 a 14 h",
        "closed_days": "Ninguno",
        "price": "Gratuito (acceso libre)",
        "currency": "CLP",
        "address": "Antonia López de Bello 900, Recoleta, Santiago",
        "contact": "lavegacentral.cl",
        "official_website": "https://www.lavegacentral.cl",
        "source": "https://www.lavegacentral.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Barrio Bellavista",
        "place_slug": "barrio_bellavista_scl",
        "category": "Barrio / Gastronomía / Cultural",
        "description": "El barrio bohemio y cultural de Santiago. Restaurantes, bares, galerías de arte, el Patio Bellavista y la Casa Museo La Chascona (Pablo Neruda). Al pie del Cerro San Cristóbal entre el río Mapocho y Recoleta.",
        "opening_hours": "Comercios y restaurantes: desde 12 h | Bares: hasta la madrugada",
        "closed_days": "Variable según local",
        "price": "Gratuito (acceso público)",
        "currency": "CLP",
        "address": "Pío Nono, Bellavista, Santiago",
        "contact": "barriobellavista.cl",
        "official_website": "https://www.barriobellavista.cl",
        "source": "https://www.barriobellavista.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "jovenes",
        "has_own_agenda": 0,
    },
    {
        "name": "Barrio Lastarria y Barrio Italia",
        "place_slug": "barrio_lastarria_scl",
        "category": "Barrio / Gastronomía / Diseño",
        "description": "Los barrios más cosmopolitas de Santiago. Lastarria: librerías, cafés y el acceso al Cerro Santa Lucía. Barrio Italia: vintage, diseñadores locales, anticuarios y la Feria Bío-Bío los fines de semana. El equivalente santiaguino de Palermo Soho.",
        "opening_hours": "Comercios: 10 a 20 h | Restaurantes y bares hasta la madrugada",
        "closed_days": "Variable según local",
        "price": "Gratuito (acceso público)",
        "currency": "CLP",
        "address": "Lastarria: José Victorino Lastarria, Santiago / Barrio Italia: Av. Italia, Providencia",
        "contact": "santiago.cl",
        "official_website": "https://www.santiago.cl",
        "source": "https://www.santiago.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "jovenes",
        "has_own_agenda": 0,
    },

    # ── MUSEOS ────────────────────────────────────────────────────────────────
    {
        "name": "Museo Chileno de Arte Precolombino",
        "place_slug": "museo_precolombino_scl",
        "category": "Museo / Arte",
        "description": "Uno de los mejores museos de arte precolombino del mundo. Más de 5.000 piezas de culturas indígenas desde México hasta Chile (4.000 a.C. al siglo XVI). Imprescindible para entender la historia de América Latina.",
        "opening_hours": "Mar a dom: 10 a 18 h",
        "closed_days": "Lunes",
        "price": "Desde $3.500 CLP adultos / Gratuito menores de 18 y primer domingo del mes - ver precolombino.cl",
        "currency": "CLP",
        "address": "Bandera 361, Santiago Centro",
        "contact": "precolombino.cl | Tel: +56 2 2928-1500",
        "official_website": "https://www.precolombino.cl",
        "source": "https://www.precolombino.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Museo de la Memoria y los Derechos Humanos",
        "place_slug": "museo_memoria_scl",
        "category": "Museo / Histórico",
        "description": "Museo dedicado a las víctimas de la dictadura militar chilena (1973-1990). Documentos, testimonios y objetos que reconstruyen la historia de la represión. Premio Iberoamericano de Arquitectura. Gratuito. Historia reciente que el turista debe conocer.",
        "opening_hours": "Mar a dom: 10 a 18 h",
        "closed_days": "Lunes",
        "price": "Gratuito",
        "currency": "CLP",
        "address": "Matucana 501, Santiago Centro",
        "contact": "museodelamemoria.cl | Tel: +56 2 2597-9600",
        "official_website": "https://www.museodelamemoria.cl",
        "source": "https://www.museodelamemoria.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "adultos",
        "has_own_agenda": 0,
    },
    {
        "name": "Casa Museo La Chascona (Pablo Neruda)",
        "place_slug": "la_chascona_scl",
        "category": "Museo / Literario",
        "description": "Una de las tres casas de Pablo Neruda en Chile, bautizada en honor a su musa Matilde Urrutia. Arquitectura laberíntica, colecciones de objetos insólitos y jardines en terrazas. En el corazón del Barrio Bellavista. Ícono cultural chileno.",
        "opening_hours": "Mar a dom: 10 a 18 h (última visita 17 h)",
        "closed_days": "Lunes",
        "price": "Desde $7.000 CLP extranjeros / $4.000 CLP chilenos - ver fundacionneruda.org",
        "currency": "CLP",
        "address": "Fernando Márquez de la Plata 0192, Bellavista, Santiago",
        "contact": "fundacionneruda.org | Tel: +56 2 2777-8741",
        "official_website": "https://www.fundacionneruda.org/la-chascona",
        "source": "https://www.fundacionneruda.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "adultos",
        "has_own_agenda": 0,
    },
    {
        "name": "Museo Nacional de Historia Natural",
        "place_slug": "mnhn_scl",
        "category": "Museo / Ciencias Naturales",
        "description": "El museo de ciencias naturales más grande de Chile (desde 1830). Colecciones de flora, fauna, mineralogía y antropología chilena. En el Parque Quinta Normal, junto a otros museos. Gratuito.",
        "opening_hours": "Mar a sab: 10 a 17:30 h | Dom: 11 a 17:30 h",
        "closed_days": "Lunes",
        "price": "Gratuito",
        "currency": "CLP",
        "address": "Interior Parque Quinta Normal s/n, Santiago",
        "contact": "mnhn.gob.cl | Tel: +56 2 2680-4600",
        "official_website": "https://www.mnhn.gob.cl",
        "source": "https://www.mnhn.gob.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "familia",
        "has_own_agenda": 0,
    },

    # ── PARQUES / ESPACIOS VERDES / ACTIVIDADES AL AIRE LIBRE ────────────────
    {
        "name": "Parque Quinta Normal",
        "place_slug": "parque_quinta_normal_scl",
        "category": "Parque / Espacio Verde / Familiar",
        "description": "El parque más antiguo y querido de Santiago (1842), con 36 hectáreas en pleno centro. Lago artificial con botes de remo ($2.500 CLP por 30 min). Patos, cisnes y pesca recreativa. Ideal para picnic en el pasto. Dentro del parque: Museo Nacional de Historia Natural (gratis), Museo Ferroviario (trenes históricos, $2.000 CLP), Museo Artequin y Museo de Ciencia y Tecnología. Los sábados y domingos hay familias enteras con termos de mate y asados portátiles. La experiencia más local y auténtica de Santiago para el viajero que quiere salir del circuito turístico.",
        "opening_hours": "Todos los días: 8 a 20 h | Botes en el lago: sab, dom y feriados 10 a 18 h",
        "closed_days": "Ninguno (parque siempre abierto)",
        "price": "Gratuito (acceso) / Botes: $2.500 CLP por 30 min / Museo Historia Natural: gratuito / Museo Ferroviario: $2.000 CLP adultos",
        "currency": "CLP",
        "address": "Av. Matucana 520, Santiago Centro (metro Quinta Normal, línea 5)",
        "contact": "parquequintanormal.cl",
        "official_website": "https://www.parquequintanormal.cl",
        "source": "https://www.parquequintanormal.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "familia",
        "has_own_agenda": 0,
    },
    {
        "name": "Ciclovías y Paseos en Bicicleta de Santiago",
        "place_slug": "ciclovias_scl",
        "category": "Deporte / Actividad al Aire Libre",
        "description": "Santiago tiene más de 400 km de ciclovías. Los más populares para turistas: Parque Forestal (borde del río Mapocho, desde Bellavista hasta el centro, completamente plano), Parque Bicentenario en Vitacura (lago, patos, muy seguro), y el Parque Metropolitano (Cerro San Cristóbal, más exigente con subidas). Bicicletería en el Parque Forestal y dentro del Cerro San Cristóbal: alquiler desde $2.000 CLP/hora. Los domingos por la mañana algunas avenidas principales cierran al tráfico para peatones y ciclistas (Cicletada Recreativa). BikeSantiago: sistema de bicicletas compartidas con estaciones en toda la ciudad, desde $500 CLP la media hora.",
        "opening_hours": "Ciclovías: siempre | Bicicleterías en parques: 9 a 18 h aprox.",
        "closed_days": "Ninguno",
        "price": "Alquiler de bicicleta: desde $2.000 CLP/hora | BikeSantiago: desde $500 CLP/30 min - ver bikesantiago.cl",
        "currency": "CLP",
        "address": "Parque Forestal: Av. Cardenal J. M. Caro s/n | Parque Bicentenario: Av. Bicentenario 4900, Vitacura",
        "contact": "bikesantiago.cl",
        "official_website": "https://www.bikesantiago.cl",
        "source": "https://www.bikesantiago.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── IDIOSINCRASIA CHILENA: FÚTBOL ─────────────────────────────────────────
    {
        "name": "Estadio Nacional Julio Martínez Pradanos",
        "place_slug": "estadio_nacional_scl",
        "category": "Estadio / Histórico",
        "description": "El estadio más emblemático de Chile (47.000 espectadores). Sede de la Selección Chilena y del Superclásico (Colo-Colo vs U de Chile). Fue utilizado como centro de detención durante la dictadura de 1973 — historia reciente que el turista debe conocer.",
        "opening_hours": "Eventos según programación - ver estadionacional.cl",
        "closed_days": "Variable",
        "price": "Ver estadionacional.cl para entradas a partidos y eventos",
        "currency": "CLP",
        "address": "Av. Grecia 2001, Ñuñoa, Santiago",
        "contact": "estadionacional.cl",
        "official_website": "https://www.estadionacional.cl",
        "source": "https://www.estadionacional.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },
    {
        "name": "Estadio Monumental David Arellano (Colo-Colo)",
        "place_slug": "estadio_monumental_colocolo_scl",
        "category": "Estadio / Fútbol",
        "description": "El estadio más grande de Chile (47.000 espectadores) y casa de Colo-Colo, el club más popular del país. El equivalente chileno de El Monumental de River. El Superclásico contra Universidad de Chile es el partido más importante del año.",
        "opening_hours": "Eventos según programación - ver colocolo.cl",
        "closed_days": "Variable según partido",
        "price": "Entradas desde $5.000 CLP (populares) - ver colocolo.cl/entradas",
        "currency": "CLP",
        "address": "Av. Marathon 5600, Macul, Santiago",
        "contact": "colocolo.cl",
        "official_website": "https://www.colocolo.cl",
        "source": "https://www.colocolo.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },

    # ── IDIOSINCRASIA CHILENA: VINO ───────────────────────────────────────────
    {
        "name": "Viña Concha y Toro – Casillero del Diablo",
        "place_slug": "vina_concha_ytoro_scl",
        "category": "Viñedo / Enoturismo",
        "description": "La viña más famosa de Chile y una de las más grandes del mundo. Tours por las bodegas, viñedos y la legendaria Casillero del Diablo. A solo 40 minutos de Santiago en Pirque (Región Metropolitana). Disponible en español e inglés. Imprescindible para el turista enófilo.",
        "opening_hours": "Lun a vie: 10 a 17 h | Sab y dom: 10 a 18 h",
        "closed_days": "Ver conchaytoro.com para fechas cerradas",
        "price": "Desde $21.000 CLP (tour básico) / Desde $30.000 CLP (tour premium con degustación) - ver conchaytoro.com/visita-las-vinas",
        "currency": "CLP",
        "address": "Av. Virginia Subercaseaux 210, Pirque, Región Metropolitana (40 min de Santiago)",
        "contact": "conchaytoro.com | Tel: +56 2 2476-5000",
        "official_website": "https://www.conchaytoro.com/visita-las-vinas",
        "source": "https://www.conchaytoro.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "adultos",
        "has_own_agenda": 0,
    },
    {
        "name": "Viña Cousiño Macul",
        "place_slug": "vina_cousino_macul_scl",
        "category": "Viñedo / Enoturismo",
        "description": "La única viña histórica dentro de los límites de Santiago (desde 1856). Tour por bodegas subterráneas del siglo XIX y degustación de vinos premium. La experiencia enoturística más accesible desde el centro de la ciudad.",
        "opening_hours": "Lun a vie: tours 10 h y 12 h | Sab: tour 11 h",
        "closed_days": "Domingos y feriados",
        "price": "Desde $18.000 CLP (tour + degustación) - ver cousinomacul.cl",
        "currency": "CLP",
        "address": "Av. Quilín 7100, Macul, Santiago",
        "contact": "cousinomacul.cl | Tel: +56 2 2351-4100",
        "official_website": "https://www.cousinomacul.cl",
        "source": "https://www.cousinomacul.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "adultos",
        "has_own_agenda": 0,
    },

    # ── IDIOSINCRASIA CHILENA: SKI EN LOS ANDES ──────────────────────────────
    {
        "name": "Valle Nevado Ski Resort",
        "place_slug": "valle_nevado_scl",
        "category": "Centro de Ski / Deportes de Invierno",
        "description": "El resort de ski más grande de Chile y uno de los más importantes de Sudamérica (3.025 msnm). A solo 46 km de Santiago (80 min en auto). Más de 30 pistas. Único en el mundo: podés esquiar en los Andes y cenar esa noche en la ciudad. Temporada: junio a octubre.",
        "opening_hours": "Temporada invierno: 9 a 17 h (según condiciones de nieve)",
        "closed_days": "Fuera de temporada (noviembre a mayo aprox.)",
        "price": "Desde $60.000 CLP día de ski adulto / Equipamiento aparte - ver vallenevado.com",
        "currency": "CLP",
        "address": "Camino Farellones km 46, Las Condes, Santiago (46 km del centro)",
        "contact": "vallenevado.com | Tel: +56 2 2477-7700",
        "official_website": "https://www.vallenevado.com",
        "source": "https://www.vallenevado.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "El Colorado / Farellones Ski Resort",
        "place_slug": "el_colorado_scl",
        "category": "Centro de Ski / Deportes de Invierno",
        "description": "El resort de ski más accesible desde Santiago (40 km, 60 min). Farellones es el pintoresco pueblo de montaña y El Colorado el resort principal. Ideal para principiantes y familias. En la misma área de montaña que La Parva y Valle Nevado.",
        "opening_hours": "Temporada invierno: 9 a 17 h",
        "closed_days": "Fuera de temporada",
        "price": "Desde $45.000 CLP día de ski - ver elcolorado.cl",
        "currency": "CLP",
        "address": "Farellones, Las Condes, Santiago (40 km del centro)",
        "contact": "elcolorado.cl | Tel: +56 2 2246-3344",
        "official_website": "https://www.elcolorado.cl",
        "source": "https://www.elcolorado.cl",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
]


def import_static_places_scl():
    print(f"\nImportando {len(PLACES)} lugares estáticos de Santiago de Chile...")
    init_db()
    city_id = get_or_create_city("Santiago de Chile", "Chile")

    imported = 0
    for place in PLACES:
        insert_place(city_id, place)
        imported += 1

    print(f"\nImportacion completada: {imported} lugares estáticos de Santiago de Chile")


if __name__ == "__main__":
    import_static_places_scl()
