"""
Importador de lugares estáticos de Rio de Janeiro.
Cubre los venues imprescindibles: praias, morros, museus, bairros icônicos.
Moeda: BRL (Real Brasileiro).
"""
import sys, os
from datetime import date
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from db.database import init_db, get_or_create_city, insert_place

TODAY = date.today().isoformat()

PLACES = [

    # ── ÍCONES / CARTÕES POSTAIS ──────────────────────────────────────────────
    {
        "name": "Cristo Redentor",
        "place_slug": "cristo_redentor_rio",
        "category": "Monumento / Patrimônio Mundial UNESCO",
        "description": "Uma das Sete Maravilhas do Mundo Moderno (2007). Estátua de 38 metros no topo do Corcovado (710 msnm). Vista panorâmica de 360° do Rio: Baía de Guanabara, Pão de Açúcar, praias e favelas. Acesso por trem do Corcovado (saída do Cosme Velho) ou van. Trem vai e vem a cada 20 min. Em dias nublados fica coberto pela neblina — verificar previsão do tempo antes de ir. Melhor horário: manhã cedo (antes das 10h) para evitar filas e neblina.",
        "opening_hours": "Todos os dias: 8 a 19 h (última subida 18h) | Trem do Corcovado: 8 a 18h",
        "closed_days": "Nenhum (sujeito a condições climáticas)",
        "price": "Trem do Corcovado: R$84 adultos / R$42 crianças (4-12 anos) - ver trem do corcovado.com.br | Van: a partir de R$30",
        "currency": "BRL",
        "address": "Parque Nacional da Tijuca, Alto da Boa Vista, Rio de Janeiro",
        "contact": "tremdocorcovado.com.br | Tel: +55 21 2558-1329",
        "official_website": "https://www.tremdocorcovado.com.br",
        "source": "https://www.tremdocorcovado.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Pão de Açúcar (Bondinho)",
        "place_slug": "pao_de_acucar_rio",
        "category": "Morro / Bondinho / Mirante",
        "description": "O símbolo do Rio. Dois bondinhos (teleféricos) chegam ao topo de 396 metros: primeiro para o Morro da Urca (vista do bondinho e praia) e depois para o Pão de Açúcar (vista completa da cidade e baía). Pôr do sol no topo é um dos espetáculos naturais mais impressionantes do mundo. Há trilhas de escalada para os mais aventureiros. No Morro da Urca tem restaurante e shows ao ar livre aos finais de semana.",
        "opening_hours": "Todos os dias: 8 a 21h (bondinho sobe a cada 20 min)",
        "closed_days": "Nenhum",
        "price": "R$158 adultos / R$79 crianças (5-12 anos) / Gratuito menores de 5 - ver bondinho.com.br",
        "currency": "BRL",
        "address": "Av. Pasteur 520, Urca, Rio de Janeiro",
        "contact": "bondinho.com.br | Tel: +55 21 2546-8400",
        "official_website": "https://www.bondinho.com.br",
        "source": "https://www.bondinho.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Estádio Maracanã",
        "place_slug": "maracana_rio",
        "category": "Estádio / Futebol / Patrimônio Histórico",
        "description": "O estádio mais famoso do mundo (capacidade: 78.838). Casa de Flamengo e Fluminense. Sede da Copa do Mundo 1950 e 2014, e dos Jogos Olímpicos 2016. Tours pelo estádio disponíveis todos os dias (vestiário, gramado, museu). O Maracanazinho (ao lado) é para vôlei, shows e eventos indoor. Assistir a um clássico Flamengo x Fluminense (Fla-Flu) aqui é uma das experiências mais intensas do esporte mundial.",
        "opening_hours": "Tours: todos os dias 9 a 17h | Jogos: conforme programação",
        "closed_days": "Nos dias de jogo o tour não opera",
        "price": "Tour: R$70 adultos / R$35 meia-entrada - ver maracana.com.br | Ingressos jogos: a partir de R$20 - ver flapasso.com.br ou futebolcard.com",
        "currency": "BRL",
        "address": "Av. Presidente Castelo Branco s/n, Maracanã, Rio de Janeiro",
        "contact": "maracana.com.br | Tel: +55 21 3111-3000",
        "official_website": "https://www.maracana.com.br",
        "source": "https://www.maracana.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },

    # ── PRAIAS ────────────────────────────────────────────────────────────────
    {
        "name": "Praia de Copacabana",
        "place_slug": "copacabana_rio",
        "category": "Praia / Espaço Público",
        "description": "A praia mais famosa do mundo: 4 km de extensão no coração do Rio. Calçadão com mosaico português, posto 6 (tradicional ponto de encontro), quiosques com água de coco e caipirinha. De manhã: corridas e exercícios físicos. À tarde: futebol de areia, vôlei e banho de sol. À noite: forró e pagode nos quiosques. O Reveillon de Copacabana reúne 2 milhões de pessoas na virada do ano. Acesso 24h, totalmente gratuito.",
        "opening_hours": "Sempre acessível (24h)",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Av. Atlântica, Copacabana, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Praia de Ipanema",
        "place_slug": "ipanema_rio",
        "category": "Praia / Espaço Público",
        "description": "A praia mais badalada do Rio e uma das mais belas do mundo. Cada trecho tem sua tribo: Posto 8 (família), Posto 9 (juventude e LGBTQIA+, conhecido como 'Cemitério dos Elefantes' pela comunidade gay dos anos 80), Posto 10 (surf). Ao entardecer, o pôr do sol visto da Pedra do Arpoador (ponta leste da praia) é parada obrigatória — os cariocas aplaudem quando o sol toca o horizonte. A Lagoa Rodrigo de Freitas fica a 5 minutos a pé.",
        "opening_hours": "Sempre acessível (24h)",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Av. Vieira Souto, Ipanema, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Pedra do Arpoador e Praia do Arpoador",
        "place_slug": "arpoador_rio",
        "category": "Mirante / Praia / Surf",
        "description": "A ponta rochosa entre Ipanema e Copacabana. O melhor lugar do Rio para ver o pôr do sol — os cariocas aplaudem coletivamente quando o sol desaparece no horizonte. Também é um dos melhores picos de surf da cidade. A pedra é livre para subir (acesso gratuito). Vista simultânea de Ipanema e Copacabana.",
        "opening_hours": "Sempre acessível",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Praça do Arpoador s/n, Ipanema, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── BAIRROS ICÔNICOS ──────────────────────────────────────────────────────
    {
        "name": "Santa Teresa e Lapa",
        "place_slug": "santa_teresa_lapa_rio",
        "category": "Bairro Histórico / Boêmio / Vida Noturna",
        "description": "Santa Teresa: o bairro mais boêmio do Rio, no alto de um morro com casarões coloniais, ateliês de artistas, restaurantes e o famoso Bondinho de Santa Teresa (VLT). Museu Chácara do Céu (arte moderna), Bar do Gomes (100 anos). A Lapa (embaixo): o coração da vida noturna carioca. Arcos da Lapa (Aqueduto Carioca do século XVIII), rodas de choro e samba nas calçadas às sextas e sábados. Centro de Tradições Nordestinas. A Lapa é brava — ir em grupo e com cuidado após meia-noite.",
        "opening_hours": "Bairros: sempre acessíveis | Bares e restaurantes: a partir das 18h | Lapa na sua melhor forma: sex e sab a partir das 22h",
        "closed_days": "Variável por estabelecimento",
        "price": "Gratuito (acesso) / Bares a partir de R$20 consumação",
        "currency": "BRL",
        "address": "Rua Almirante Alexandrino, Santa Teresa / Av. Mem de Sá, Lapa, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "adultos",
        "has_own_agenda": 0,
    },
    {
        "name": "Centro Histórico do Rio — Praça XV e Arredores",
        "place_slug": "centro_historico_rio",
        "category": "Centro Histórico / Patrimônio",
        "description": "O centro histórico do Rio concentra séculos de história numa área caminhável. Praça XV de Novembro: Paço Imperial (exposições gratuitas), Ferry para Niterói (R$8, vista da Baía de Guanabara). Rua do Ouvidor (a Wall Street do século XIX). Confeitaria Colombo (1894, café histórico numa arquitetura art nouveau deslumbrante). Real Gabinete Português de Leitura (uma das bibliotecas mais belas do mundo, acesso gratuito). Museu Histórico Nacional. Igreja Nossa Senhora da Candelária.",
        "opening_hours": "Praça XV: sempre acessível | Paço Imperial: ter a dom 12 a 18h | Confeitaria Colombo: seg a sab 9 a 20h | Real Gabinete: seg a sex 9 a 18h",
        "closed_days": "Variável por atração",
        "price": "Maioria gratuito / Confeitaria Colombo: café a partir de R$15",
        "currency": "BRL",
        "address": "Praça XV de Novembro s/n, Centro, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── NATUREZA / PARQUES ────────────────────────────────────────────────────
    {
        "name": "Parque Nacional da Tijuca",
        "place_slug": "tijuca_rio",
        "category": "Parque Nacional / Natureza / Trilhas",
        "description": "A maior floresta urbana do mundo: 3.953 hectares de Mata Atlântica dentro da cidade do Rio. Trilhas para todos os níveis: Cascatinha Taunay (fácil, 20 min), Pico da Tijuca (moderado, 2h, 1.021m com vista incrível), Vista Chinesa (mirante com vista da cidade). Piscinas naturais no Açude da Solidão. O Cristo Redentor fica dentro do parque. Fauna: micos, tucanos, saguis. Ideal para escapar do calor carioca.",
        "opening_hours": "Todos os dias: 8 a 17h (trilhas fecham antes do anoitecer)",
        "closed_days": "Nenhum",
        "price": "Gratuito (acesso ao parque) / Guias opcionais a partir de R$80",
        "currency": "BRL",
        "address": "Estrada da Cascatinha 850, Alto da Boa Vista, Rio de Janeiro",
        "contact": "parquedatijuca.com.br | Tel: +55 21 2492-2252",
        "official_website": "https://www.parquedatijuca.com.br",
        "source": "https://www.parquedatijuca.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Lagoa Rodrigo de Freitas",
        "place_slug": "lagoa_rio",
        "category": "Parque / Lago / Atividades ao Ar Livre",
        "description": "Lagoa artificial de 7 km² rodeada de montanhas entre Ipanema e o Jardim Botânico. Ciclovia de 7,5 km ao redor do lago (aluguel de bicicletas: R$15/hora). Pedalinhos e caiaques para alugar. Corridas e caminhadas. Restaurantes e quiosques na beira d'água. No Natal: a maior árvore de Natal flutuante do mundo (30 metros). Vista do Cristo Redentor iluminado à noite. Acesso 24h e totalmente gratuito para caminhar.",
        "opening_hours": "Sempre acessível | Bicicletas: 6 a 22h | Pedalinhos: 9 a 17h",
        "closed_days": "Nenhum",
        "price": "Gratuito (ciclovia e caminhada) / Bicicletas: R$15/hora / Pedalinho: R$20/30 min",
        "currency": "BRL",
        "address": "Av. Epitácio Pessoa s/n, Lagoa, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Jardim Botânico do Rio de Janeiro",
        "place_slug": "jardim_botanico_rio",
        "category": "Parque / Jardim Botânico / Natureza",
        "description": "Um dos mais belos jardins botânicos do mundo (1808, fundado por D. João VI). 54 hectares com mais de 6.500 espécies. A famosa Alameda das Palmeiras Imperiais (Imperial, 40 metros de altura) é a imagem mais reproduzida do jardim. Orquidário, jardim japonês, lago com vitórias-régias gigantes. Micos e anuns correm livres pelos caminhos. A menos de 10 minutos a pé do Parque Lage (acesso à trilha do Corcovado pela floresta).",
        "opening_hours": "Ter a dom: 8 a 17h (última entrada 16h)",
        "closed_days": "Segunda-feira",
        "price": "R$20 adultos / R$10 meia-entrada / Gratuito menores de 7 anos - ver jbrj.gov.br",
        "currency": "BRL",
        "address": "Rua Jardim Botânico 1008, Jardim Botânico, Rio de Janeiro",
        "contact": "jbrj.gov.br | Tel: +55 21 3723-8000",
        "official_website": "https://www.jbrj.gov.br",
        "source": "https://www.jbrj.gov.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── MUSEUS / CULTURA ──────────────────────────────────────────────────────
    {
        "name": "Museu do Amanhã",
        "place_slug": "museu_amanha_rio",
        "category": "Museu / Ciência / Tecnologia",
        "description": "Um dos museus de ciência mais modernos do mundo, no Píer Mauá (Zona Portuária). Projeto de Santiago Calatrava. Explora o futuro da humanidade em 5 áreas: Cosmos, Terra, Antropoceno, Amanhãs e Nós. Exposições interativas e imersivas, muito popular entre crianças e jovens. A praça externa com a orla revitalizada do Porto Maravilha tem ótimas vistas da Baía de Guanabara e da Ponte Rio-Niterói.",
        "opening_hours": "Ter a dom: 10 a 18h (última entrada 17h)",
        "closed_days": "Segunda-feira",
        "price": "R$30 adultos / R$15 meia-entrada / Gratuito terças e primeira quarta do mês - ver museudoamanha.org.br",
        "currency": "BRL",
        "address": "Praça Mauá 1, Centro, Rio de Janeiro (VLT: Parada Museu do Amanhã)",
        "contact": "museudoamanha.org.br | Tel: +55 21 3812-1800",
        "official_website": "https://museudoamanha.org.br",
        "source": "https://museudoamanha.org.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },
    {
        "name": "Museu de Arte do Rio (MAR)",
        "place_slug": "mar_rio",
        "category": "Museu / Arte",
        "description": "Museu de arte contemporânea dedicado ao Rio de Janeiro e sua gente. Dois prédios históricos unidos por uma marquise ondulante. Vista panorâmica do Porto Maravilha e da Baía de Guanabara do mirante. Exposições temporárias de artistas cariocas e internacionais. Ao lado do Museu do Amanhã — visita combinada recomendada.",
        "opening_hours": "Ter a dom: 10 a 17h (última entrada 16h)",
        "closed_days": "Segunda-feira",
        "price": "R$20 adultos / R$10 meia-entrada / Gratuito terças - ver museudeartedorio.org.br",
        "currency": "BRL",
        "address": "Praça Mauá 5, Centro, Rio de Janeiro",
        "contact": "museudeartedorio.org.br | Tel: +55 21 3031-2741",
        "official_website": "https://www.museudeartedorio.org.br",
        "source": "https://www.museudeartedorio.org.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },
    {
        "name": "Centro Cultural Banco do Brasil Rio (CCBB Rio)",
        "place_slug": "ccbb_rio",
        "category": "Centro Cultural / Arte / Exposições",
        "description": "Um dos centros culturais mais importantes do Brasil. Exposições de arte de alto nível, cinema, teatro, música e gastronomia. Prédio histórico do século XX no Centro do Rio. Programação intensa e variada, com exposições internacionais. Geralmente com obras de grandes artistas. O café e a livraria dentro do espaço são muito agradáveis.",
        "opening_hours": "Qua a seg: 9 a 21h",
        "closed_days": "Terça-feira",
        "price": "Maioria das exposições gratuitas / Alguns espetáculos com ingresso - ver ccbb.com.br/rio-de-janeiro",
        "currency": "BRL",
        "address": "Rua Primeiro de Março 66, Centro, Rio de Janeiro",
        "contact": "ccbb.com.br | Tel: +55 21 3808-2020",
        "official_website": "https://ccbb.com.br/rio-de-janeiro",
        "source": "https://ccbb.com.br/rio-de-janeiro",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },
    {
        "name": "Teatro Municipal do Rio de Janeiro",
        "place_slug": "teatro_municipal_rio",
        "category": "Teatro / Ópera / Música Clássica",
        "description": "O principal teatro lírico do Rio de Janeiro (1909), inspirado na Ópera de Paris. Sede da Orquestra Sinfônica Brasileira e do Balé do Theatro Municipal. Temporadas de ópera, ballet e concertos. Visitas guiadas ao interior suntuoso com mármores, lustres e pinturas do teto. Localizado na Cinelândia, no centro histórico.",
        "opening_hours": "Visitas guiadas: ter a sex 12 e 15h, sab 11 e 14h | Espetáculos conforme temporada",
        "closed_days": "Segunda-feira",
        "price": "Visita guiada: R$10 / Espetáculos: a partir de R$20 - ver theatromunicipal.rj.gov.br",
        "currency": "BRL",
        "address": "Praça Floriano s/n, Cinelândia, Centro, Rio de Janeiro",
        "contact": "theatromunicipal.rj.gov.br | Tel: +55 21 2332-9134",
        "official_website": "https://theatromunicipal.rj.gov.br",
        "source": "https://theatromunicipal.rj.gov.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "adultos",
        "has_own_agenda": 1,
    },

    # ── EXPERIÊNCIAS ÚNICAS ───────────────────────────────────────────────────
    {
        "name": "Sambódromo — Marquês de Sapucaí",
        "place_slug": "sambodromo_rio",
        "category": "Carnaval / Samba / Espetáculo",
        "description": "O palco do Carnaval do Rio: 700 metros de passarela onde os milhares de foliões das escolas de samba desfilam em fevereiro. Fora do Carnaval: shows, eventos e visitas. Nos fins de semana de outubro a fevereiro, os ensaios técnicos das escolas de samba (gratuitos ou com ingresso barato) permitem ver o processo de preparação do maior espetáculo do mundo. As quadras das escolas de samba no subúrbio (Mangueira, Portela, Beija-Flor) têm rodas de samba abertas nos fins de semana.",
        "opening_hours": "Carnaval: fevereiro | Ensaios: out a jan, sex e sab a partir das 22h | Visitas: conforme programação",
        "closed_days": "Variável",
        "price": "Ensaios técnicos: R$20 a R$50 | Desfiles de Carnaval: a partir de R$150 (arquibancada) - ver rio-carnaval.com",
        "currency": "BRL",
        "address": "Rua Marquês de Sapucaí s/n, Cidade Nova, Rio de Janeiro",
        "contact": "rio-carnaval.com",
        "official_website": "https://www.rio-carnaval.com",
        "source": "https://www.rio-carnaval.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },
    {
        "name": "Favela Santa Marta e Tours de Favela",
        "place_slug": "favela_tour_rio",
        "category": "Turismo Cultural / Experiência Local",
        "description": "Santa Marta (Dona Marta) foi a primeira favela pacificada do Rio (2008) e é hoje ponto de visita turística consolidado. Teleférico comunitário gratuito sobe até o alto do morro, com vista de 360° da cidade. Mural gigante de Michael Jackson (onde filmou o clipe They Don't Care About Us). Arte urbana por toda parte. Tours guiados com moradores saem do Largo do Machado. Importante: ir com agência local ou guia comunitário, nunca entrar sozinho sem conhecer.",
        "opening_hours": "Teleférico: seg a sex 8 a 20h, sab 8 a 16h | Tours: conforme agência",
        "closed_days": "Dom (teleférico fechado)",
        "price": "Teleférico: gratuito para moradores / R$2 turistas | Tour guiado: a partir de R$80 por pessoa",
        "currency": "BRL",
        "address": "Rua Marechal Francisco de Moura, Botafogo (acesso pela Rua São Clemente)",
        "contact": "visit.rio",
        "official_website": "https://visit.rio/roteiros/santa-marta",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "adultos",
        "has_own_agenda": 0,
    },
    {
        "name": "Feira de São Cristóvão (Centro Luiz Gonzaga)",
        "place_slug": "feira_sao_cristovao_rio",
        "category": "Feira / Gastronomia Nordestina / Cultura Popular",
        "description": "A maior feira nordestina fora do Nordeste. 700 barracas com comida, artesanato, música ao vivo e forró. Baião de dois, carne de sol, tapioca, cachaça. Bailes de forró toda sexta e sábado à noite. Uma imersão na cultura nordestina dentro do Rio — completamente diferente da imagem que o turista tem da cidade. Funciona 24h nos fins de semana. Inesquecível.",
        "opening_hours": "Qui a dom: 10h a segunda 22h (funciona ininterrupto no fim de semana)",
        "closed_days": "Segunda a quarta",
        "price": "Gratuito (entrada) / Comidas a partir de R$15",
        "currency": "BRL",
        "address": "Campo de São Cristóvão s/n, São Cristóvão, Rio de Janeiro",
        "contact": "feiradesaocristovao.org.br",
        "official_website": "https://www.feiradesaocristovao.org.br",
        "source": "https://www.feiradesaocristovao.org.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── MIRANTES / TRILHAS GRÁTIS ─────────────────────────────────────────────
    {
        "name": "Escadaria Selarón (Escadaria do Cuartel)",
        "place_slug": "selaron_rio",
        "category": "Arte Urbana / Mirante / Ícone Cultural",
        "description": "215 degraus cobertos por mais de 2.000 azulejos coloridos de 60 países — obra do artista chileno Jorge Selarón que dedicou sua vida a embelezar a escadaria entre Santa Teresa e a Lapa. Ícone absoluto do Rio: fotografada por todo mundo, cenário de videoclipes e campanhas internacionais. Selarón foi encontrado morto na própria escadaria em 2013, tornando-a ainda mais emblemática. Acesso gratuito 24h, mas melhor pela manhã para fazer fotos sem multidão.",
        "opening_hours": "Sempre acessível (24h)",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Rua Joaquim Silva s/n (entre Santa Teresa e Lapa), Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Arcos da Lapa (Aqueduto Carioca)",
        "place_slug": "arcos_lapa_rio",
        "category": "Patrimônio Histórico / Ponto Turístico",
        "description": "Aqueduto do século XVIII (1723) com 42 arcos de pedra que transportava água da Carioca para a cidade. Hoje é o símbolo da Lapa e serve de viaduto para o Bondinho de Santa Teresa (VLT). A praça embaixo é um dos melhores points da vida noturna carioca: rodas de samba, capoeira e artistas de rua principalmente nas sextas e sábados. O visual dos arcos iluminados à noite com a cidade ao fundo é deslumbrante.",
        "opening_hours": "Sempre acessível (exterior 24h) | VLT Santa Teresa: ter a dom 8 a 22h",
        "closed_days": "Nenhum (exterior)",
        "price": "Gratuito (ver os arcos) / VLT Santa Teresa: R$5",
        "currency": "BRL",
        "address": "Av. Mem de Sá s/n, Lapa, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Morro Dois Irmãos — Trilha e Mirante",
        "place_slug": "dois_irmaos_rio",
        "category": "Trilha / Mirante / Natureza",
        "description": "Os dois picos gêmeos de granito (533 m) que dominam o horizonte de Ipanema e Leblon são um dos mirantes mais impressionantes do Rio. A trilha saindo de Vidigal (favela entre Ipanema e São Conrado) leva aprox. 1h30 ida com guia obrigatório. Do topo: vista privilegiada de Ipanema, Lagoa, Cristo, Pão de Açúcar e o oceano. É necessário contratar guia local (R$80-120 por pessoa) — além de seguro, contribui com a comunidade de Vidigal. Uma das experiências mais memoráveis do Rio para quem gosta de natureza.",
        "opening_hours": "Saídas diárias: 6h e 8h (chegar cedo evita calor e nuvens)",
        "closed_days": "Nenhum (sujeito ao clima)",
        "price": "Guia obrigatório: R$80-120 por pessoa (agendar com antecedência em vidigal.com.br ou TripAdvisor)",
        "currency": "BRL",
        "address": "Acesso pelo Vidigal, entre Leblon e São Conrado, Rio de Janeiro",
        "contact": "vidigal.com.br",
        "official_website": "https://visit.rio/roteiros/morro-dois-irmaos",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "adultos (boa forma física)",
        "has_own_agenda": 0,
    },
    {
        "name": "Mirante Dona Marta",
        "place_slug": "mirante_dona_marta_rio",
        "category": "Mirante / Vista Panorâmica / Gratuito",
        "description": "O mirante oficial com a vista mais famosa do Rio: o Cristo Redentor em primeiro plano com a cidade, a Baía de Guanabara e as praias ao fundo — a foto que aparece em todos os cartões postais do Rio. Fica no alto do Morro Dona Marta, dentro da favela Santa Marta. Acesso pelo VLT comunitário (gratuito para turistas no teleférico da Santa Marta) ou de táxi/carro até o topo. Aberto 24h. Ao entardecer e à noite, com o Cristo iluminado, é especialmente deslumbrante.",
        "opening_hours": "Sempre acessível (24h) | Teleférico Santa Marta: seg a sex 8-20h, sab 8-16h",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Alto do Morro Dona Marta, Santa Marta / Botafogo, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Parque Lage e Trilha do Corcovado pela Floresta",
        "place_slug": "parque_lage_rio",
        "category": "Parque / Trilha / Arte / Café",
        "description": "Parque público gratuito com uma mansão Renascentista do início do século XX (hoje Escola de Artes Visuais) rodeada de Mata Atlântica. O café da mansão é um dos mais instagramados do Rio. Da portaria dos fundos sai a trilha oficial (gratuita, 3h ida e volta) que sobe até o Cristo Redentor pela floresta — a alternativa mais bonita e barata ao trem do Corcovado. Vista do Rio entre as árvores. A trilha é moderada, precisa de boa condição física e calçado adequado.",
        "opening_hours": "Parque: todos os dias 8 a 18h | Café/Escola: ter a dom 8 a 18h | Trilha: fechar portão antes das 13h para garantir volta",
        "closed_days": "Segunda-feira (Escola de Artes)",
        "price": "Gratuito (parque e trilha) / Café: a partir de R$15",
        "currency": "BRL",
        "address": "Rua Jardim Botânico 414, Jardim Botânico, Rio de Janeiro",
        "contact": "eavparquelage.rj.gov.br",
        "official_website": "https://eavparquelage.rj.gov.br",
        "source": "https://eavparquelage.rj.gov.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── PRAIAS ALÉM DE IPANEMA E COPACABANA ───────────────────────────────────
    {
        "name": "Praia do Leme",
        "place_slug": "leme_rio",
        "category": "Praia / Bairro Tranquilo",
        "description": "A praia mais tranquila e menos lotada da Zona Sul — fica na ponta norte de Copacabana. Ambiente familiar e de vizinhança, menos turística. O Forte do Leme (Área de Proteção Ambiental) fica no morro ao lado: trilha de 40 min com muitos saguis e vista bonita do Pão de Açúcar. Acesso ao forte: seg a sex 8-16h, ingresso simbólico. A Rua Gustavo Sampaio tem bons restaurantes e botequins a preço de bairro.",
        "opening_hours": "Praia: sempre | Forte do Leme: seg a sex 8 a 16h",
        "closed_days": "Forte fecha fins de semana e feriados",
        "price": "Gratuito (praia) / Forte do Leme: R$5",
        "currency": "BRL",
        "address": "Av. Atlântica s/n, Leme, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Praia da Barra da Tijuca",
        "place_slug": "barra_tijuca_rio",
        "category": "Praia / Natureza / Surf",
        "description": "A maior praia do Rio: 18 km de extensão, águas mais limpas que Ipanema e Copacabana, areia branca e ondas ideais para surf. Menos densa que as praias da Zona Sul, com vibe mais tranquila. A Barra tem muitos condomínios fechados (é uma 'Miami carioca'), mas a praia é pública. Fica a ~40 min de ônibus do Centro. Bom para quem quer praia com menos multidão. Av. Lúcio Costa é o orla principal com quiosques, restaurantes e lojas.",
        "opening_hours": "Sempre acessível (24h)",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Av. Lúcio Costa s/n, Barra da Tijuca, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Praia de Urca e Bairro da Urca",
        "place_slug": "urca_rio",
        "category": "Bairro / Praia Tranquila / Mirante",
        "description": "O bairro mais tranquilo e bucólico do Rio, aos pés do Pão de Açúcar. Casas coloniais, ruas arborizadas, macacos soltos e um ritmo completamente diferente do resto da cidade. A Praia de Urca é minúscula (300 m) mas pitoresca — pescadores locais, crianças, e frequentemente lontras e polvos na orla. O Mureta da Urca (na Praia Vermelha) é famoso: jovens e cariocas se reúnem aqui ao entardecer com viola, cerveja e churrasquinho. Vista perfeita do Pão de Açúcar sem pagar o bondinho.",
        "opening_hours": "Sempre acessível (bairro e praia 24h)",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Praia de Urca / Av. João Luís Alves s/n, Urca, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── CULTURA / MUSEUS ADICIONAIS ───────────────────────────────────────────
    {
        "name": "Real Gabinete Português de Leitura",
        "place_slug": "gabinete_portugues_rio",
        "category": "Biblioteca Histórica / Patrimônio Cultural",
        "description": "Uma das bibliotecas mais belas do mundo — interior neo-manuelino dourado com mais de 350.000 volumes, incluindo raridades do século XVI. Fundada em 1837 por imigrantes portugueses. A única razão para visitar já valeria a viagem: o átrio central com três andares de estantes de madeira entalhada, vitrais e esculturas é de tirar o fôlego. Totalmente gratuita e no Centro histórico, a 5 min da Praça XV. Quase nenhum turista sabe que existe.",
        "opening_hours": "Seg a sex: 9 a 18h | Sab: 9 a 13h",
        "closed_days": "Domingo e feriados",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Rua Luís de Camões 30, Centro, Rio de Janeiro",
        "contact": "realgabinete.com.br | Tel: +55 21 2221-3138",
        "official_website": "https://www.realgabinete.com.br",
        "source": "https://www.realgabinete.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Confeitaria Colombo",
        "place_slug": "colombo_rio",
        "category": "Café Histórico / Gastronomia / Patrimônio",
        "description": "O café mais famoso e histórico do Rio (1894). Interior art nouveau deslumbrante com espelhos belgas de 1,7m, vitrais, mármore e jacarandá. Frequentado por presidentes, escritores e artistas por mais de um século. Famoso pelo bufê de feijoada aos sábados (R$98 por pessoa, reserva recomendada) e pelos doces tradicionais. O ambiente em si já vale a visita mesmo sem comer — não cobram ingresso para entrar e apreciar o espaço. Fica no Centro histórico.",
        "opening_hours": "Seg a sab: 9 a 20h | Dom: fechado (exceto filial do Forte de Copacabana)",
        "closed_days": "Domingo (filial principal)",
        "price": "Café e salgados a partir de R$15 / Bufê feijoada sab: R$98 por pessoa",
        "currency": "BRL",
        "address": "Rua Gonçalves Dias 32, Centro, Rio de Janeiro",
        "contact": "confeitariacolombo.com.br | Tel: +55 21 2505-1500",
        "official_website": "https://www.confeitariacolombo.com.br",
        "source": "https://www.confeitariacolombo.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Museu de Arte Moderna do Rio (MAM)",
        "place_slug": "mam_rio",
        "category": "Museu / Arte Moderna / Parque",
        "description": "Um dos maiores museus de arte moderna da América Latina, no Aterro do Flamengo. O prédio modernista de Affonso Reidy (1948) é obra de arte em si. Acervo com mais de 15.000 obras de artistas brasileiros e internacionais. O Parque do Aterro do Flamengo ao redor (148 hectares ao beira da Baía de Guanabara) é o maior parque urbano do Rio — ciclovia, pistas de skate, campo de futebol e vistas do Pão de Açúcar. O parque é totalmente gratuito.",
        "opening_hours": "Museu: ter a sex 12 a 18h, sab dom e feriados 12 a 18h | Parque Aterro: sempre",
        "closed_days": "Segunda-feira",
        "price": "Museu: R$30 adultos / R$15 meia / Gratuito terças - ver mamrio.org.br | Parque: Gratuito",
        "currency": "BRL",
        "address": "Av. Infante Dom Henrique 85, Parque do Flamengo, Rio de Janeiro",
        "contact": "mamrio.org.br | Tel: +55 21 3883-5600",
        "official_website": "https://mamrio.org.br",
        "source": "https://mamrio.org.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
    },
    {
        "name": "Museu Histórico Nacional",
        "place_slug": "museu_historico_rio",
        "category": "Museu / História do Brasil",
        "description": "O maior e mais importante museu de história do Brasil. Acervo de 300.000 itens: trono imperial de Dom Pedro II, carruagens reais, armaduras coloniais, documentos da chegada de D. João VI, instrumentos científicos, arte sacra e arqueologia. Instalado num conjunto de edificações históricas na Praça XV, no Centro. Gratuito aos domingos.",
        "opening_hours": "Ter a sex: 10 a 17:30h | Sab, dom e feriados: 14 a 18h",
        "closed_days": "Segunda-feira",
        "price": "R$10 adultos / R$5 meia-entrada / Gratuito domingos - ver museuhistoriconacional.com.br",
        "currency": "BRL",
        "address": "Praça Marechal Âncora s/n, Centro, Rio de Janeiro",
        "contact": "museuhistoriconacional.com.br | Tel: +55 21 3299-0324",
        "official_website": "https://www.museuhistoriconacional.com.br",
        "source": "https://www.museuhistoriconacional.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "Quinta da Boa Vista e BioParque Rio",
        "place_slug": "quinta_boa_vista_rio",
        "category": "Parque / Zoológico / Família",
        "description": "Antigo parque imperial (1809), hoje parque público gratuito no bairro de São Cristóvão. O Museu Nacional funcionava aqui até o incêndio de 2018 (em reconstrução). O BioParque Rio (antigo zoológico, reaberto em 2021 como bioparque moderno) tem 2.500 animais de 350 espécies: leões, girafas, hipopótomos, pinguins, jacarés. Ideal para crianças e famílias. O parque ao redor tem lagos, quiosques e espaço para piquenique. A 20 min do Sambódromo.",
        "opening_hours": "Parque: todos os dias 9 a 17h | BioParque: ter a dom 9 a 17h (bilheteria até 16h)",
        "closed_days": "Segunda-feira (BioParque)",
        "price": "Parque: Gratuito / BioParque: R$44 adultos / R$22 meia-entrada / Gratuito menores de 2 anos - ver bioparquecarioca.com.br",
        "currency": "BRL",
        "address": "Av. Pedro II s/n, São Cristóvão, Rio de Janeiro",
        "contact": "bioparquecarioca.com.br | Tel: +55 21 3878-4200",
        "official_website": "https://www.bioparquecarioca.com.br",
        "source": "https://www.bioparquecarioca.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "familias com crianças",
        "has_own_agenda": 0,
    },
    {
        "name": "Catedral Metropolitana do Rio (São Sebastião)",
        "place_slug": "catedral_metro_rio",
        "category": "Igreja / Patrimônio Arquitetônico",
        "description": "Uma das igrejas mais incomuns do mundo: forma de pirâmide truncada de concreto (1979, projeto Edgar de Oliveira da Fonseca) inspirada nas pirâmides maias. Capacidade para 20.000 pessoas. O interior é completamente diferente de qualquer catedral tradicional: quatro immensos vitrais de 64 metros de altura em cruz que inundam tudo de luz colorida. Um espetáculo visual gratuito, a 5 min dos Arcos da Lapa.",
        "opening_hours": "Seg a sab: 7 a 17h | Dom: 8 a 17h | Missas: dom 10h",
        "closed_days": "Nenhum",
        "price": "Gratuito",
        "currency": "BRL",
        "address": "Av. República do Chile 245, Centro, Rio de Janeiro",
        "contact": "catedral.art.br | Tel: +55 21 2240-2669",
        "official_website": "https://www.catedral.art.br",
        "source": "https://www.catedral.art.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },

    # ── EXPERIÊNCIAS / ATIVIDADES ─────────────────────────────────────────────
    {
        "name": "Parapente em São Conrado — Pedra Bonita",
        "place_slug": "parapente_sao_conrado_rio",
        "category": "Esporte de Aventura / Vista Aérea",
        "description": "Saltar de parapente da Pedra Bonita (517 m) e planar sobre as praias de São Conrado, Leblon e Ipanema com vista do Cristo, Pão de Açúcar e a cidade inteira é uma das experiências mais emocionantes disponíveis no Rio. Voos duplos (com piloto, sem experiência prévia necessária) duram 10-15 min e pousam na própria Praia de São Conrado. Rio tem as condições de vento mais seguras e consistentes do mundo para parapente urbano. Operadoras licenciadas: Just Fly (a mais tradicional), Delta Flight.",
        "opening_hours": "Todos os dias: 8 a 16h (sujeito a condições de vento)",
        "closed_days": "Nenhum (sujeito ao clima)",
        "price": "R$450 - R$550 por pessoa (voo duplo com piloto, ~15 min) — ver justfly.com.br",
        "currency": "BRL",
        "address": "Estrada das Canoas 2310 (decolagem) / Praia de São Conrado (pouso), Rio de Janeiro",
        "contact": "justfly.com.br | Tel: +55 21 3322-2286",
        "official_website": "https://www.justfly.com.br",
        "source": "https://www.justfly.com.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "adultos (aventureiros)",
        "has_own_agenda": 0,
    },
    {
        "name": "Feira de Antiguidades de Ipanema (Hippy Fair)",
        "place_slug": "feira_ipanema_rio",
        "category": "Feira / Artesanato / Domingo",
        "description": "Tradicional feira de artesanato e antiguidades que acontece todos os domingos na Praça General Osório, em Ipanema (desde 1968). Mais de 200 barracas com bijuterias, esculturas, quadros, roupas de brechó, artesanato indígena, ervas e comidas. O ambiente é descontraído e colorido — muito carioca. Uma boa maneira de comprar lembranças autenticas e baratas sem ir a loja de souvenir. Combinar com café da manhã no Garota de Ipanema (a 3 min) e praia depois.",
        "opening_hours": "Domingos: 9 a 18h",
        "closed_days": "Todos os dias exceto domingo",
        "price": "Gratuito (entrada) / Artesanato a partir de R$10",
        "currency": "BRL",
        "address": "Praça General Osório s/n, Ipanema, Rio de Janeiro",
        "contact": "visit.rio",
        "official_website": "https://visit.rio",
        "source": "https://visit.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
    {
        "name": "AquaRio — Aquário Marinho do Rio",
        "place_slug": "aquario_rio",
        "category": "Aquário / Família / Ciência",
        "description": "O maior aquário marinho da América do Sul (23.000 m², inaugurado em 2016). 350 espécies marinhas, 5 milhões de litros d'água. Destaque para o tubo de acrílico de 10m onde tubarões-touro, arraias e tartarugas nadam ao redor dos visitantes. Experiência de mergulho com tubarões disponível (reserva antecipada). Localizado na Zona Portuária, ao lado do Museu do Amanhã — visita combinada recomendada.",
        "opening_hours": "Ter a dom: 10 a 18h (última entrada 16:30h)",
        "closed_days": "Segunda-feira",
        "price": "R$80 adultos / R$40 meia-entrada / Gratuito menores de 2 anos — ver aquario.rio",
        "currency": "BRL",
        "address": "Av. Plínio Carlos Leme 400, Gamboa, Rio de Janeiro (Zona Portuária)",
        "contact": "aquario.rio | Tel: +55 21 3279-8200",
        "official_website": "https://aquario.rio",
        "source": "https://aquario.rio",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "familias con crianças",
        "has_own_agenda": 0,
    },
    {
        "name": "Museu da República — Palácio do Catete",
        "place_slug": "museu_republica_rio",
        "category": "Museu / História / Palácio",
        "description": "O palácio onde governaram todos os presidentes do Brasil de 1897 a 1960 (quando a capital foi transferida para Brasília). Getúlio Vargas se suicidou aqui em 1954 — a sala com os móveis originais e o pijama que vestia quando morreu estão preservados. Jardins magníficos (gratuitos) com lago, pavões e esculturas. A 10 min a pé do Sambódromo e do metrô Catete.",
        "opening_hours": "Ter a sex: 10 a 17h | Sab e dom: 14 a 18h | Jardins: ter a dom 9 a 17h",
        "closed_days": "Segunda-feira",
        "price": "R$10 adultos / R$5 meia-entrada / Gratuito quartas e domingos — ver museudarepublica.museus.gov.br",
        "currency": "BRL",
        "address": "Rua do Catete 153, Catete, Rio de Janeiro",
        "contact": "museudarepublica.museus.gov.br | Tel: +55 21 3235-2650",
        "official_website": "https://museudarepublica.museus.gov.br",
        "source": "https://museudarepublica.museus.gov.br",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
    },
]


def import_static_places_rio():
    print(f"\nImportando {len(PLACES)} lugares estáticos de Rio de Janeiro...")
    init_db()
    city_id = get_or_create_city("Rio de Janeiro", "Brasil")

    for place in PLACES:
        insert_place(city_id, place)

    print(f"\nImportacao completada: {len(PLACES)} lugares de Rio de Janeiro")


if __name__ == "__main__":
    import_static_places_rio()
