"""
Importador de lugares estáticos de París.
Museos, monumentos, barrios, parques y experiencias icónicas.
Moneda: EUR.
"""
import sys, os
from datetime import date
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from db.database import init_db, get_or_create_city, insert_place

TODAY = date.today().isoformat()

PLACES = [

    # ── MONUMENTOS ICÓNICOS ───────────────────────────────────────────────────
    {
        "name": "Tour Eiffel",
        "place_slug": "tour_eiffel_paris",
        "category": "Monumento / Icono Mundial",
        "description": "El símbolo más reconocido del mundo, construido por Gustave Eiffel para la Exposición Universal de 1889. 330 metros de altura (con antena). Tres plantas: planta 1 (57 m, restaurante 58 Tour Eiffel), planta 2 (115 m, restaurante Jules Verne con estrella Michelin), cima (276 m, vista de 70 km en día despejado). El espectáculo de luces cada hora al anochecer dura 5 minutos — verlo desde el Trocadéro (gratis) es una experiencia mágica. Colas enormes — comprar online con meses de antelación. Subir las escaleras hasta la planta 2 es más barato y evita parte de la cola.",
        "opening_hours": "Todos los días: 9:30-23:45h (jul-ago: 9-0:45h) | Escaleras: 9:30-18:30h",
        "closed_days": "Ninguno",
        "price": "Escaleras hasta P2: €11,30 adultos / Ascensor P2: €18,80 / Ascensor cima: €29,40 — ver toureiffel.paris",
        "currency": "EUR",
        "address": "Champ de Mars, 5 Av. Anatole France, 75007 Paris",
        "contact": "toureiffel.paris | Tel: +33 8 92 70 12 39",
        "official_website": "https://www.toureiffel.paris",
        "source": "https://www.toureiffel.paris",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Notre-Dame de Paris",
        "place_slug": "notre_dame_paris",
        "category": "Catedral / Patrimonio / Arquitectura Gótica",
        "description": "La catedral gótica más famosa del mundo, en la Île de la Cité. Construida entre 1163 y 1345. Sufrió un devastador incendio el 15 de abril de 2019 que destruyó la flecha y parte de la nave. Reabrió sus puertas en diciembre de 2024 completamente restaurada, más bella que nunca. Las vidrieras del rosetón norte (siglo XIII, originales) son consideradas las más bellas de la Edad Media. Desde la torre de las campanas (acceso por la Rue du Cloître): las famosas gárgolas y vista de París. El exterior y la plaza frente a la catedral son siempre accesibles y gratuitos.",
        "opening_hours": "Catedral: lun-vie 8-19h, sáb-dom 8-19:30h | Torres: 10-18:30h (temporada alta hasta 23h)",
        "closed_days": "Torres: 1 enero, 1 mayo, 25 diciembre",
        "price": "Catedral: Gratuita | Torres: €15 adultos / Gratuito menores 18 — ver notredamedeparis.fr",
        "currency": "EUR",
        "address": "6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris (Île de la Cité)",
        "contact": "notredamedeparis.fr",
        "official_website": "https://www.notredamedeparis.fr",
        "source": "https://www.notredamedeparis.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Arc de Triomphe",
        "place_slug": "arc_triomphe_paris",
        "category": "Monumento / Mirador / Patrimonio",
        "description": "Construido por Napoleón en 1806 para conmemorar sus victorias. En el centro de la Place de l'Étoile, donde confluyen 12 avenidas incluyendo los Champs-Élysées. La terraza en lo alto (50 m) ofrece la mejor vista de los Champs-Élysées y la perspectiva histórica de París desde el eje Este-Oeste (de la Pirámide del Louvre hasta la Grande Arche de La Défense). Llama del soldado desconocido que arde sin interrupciones desde 1923 — ceremonia de renovación cada día a las 18:30h. Acceso: NO atravesar la plaza (prohibido y peligroso), usar el túnel peatonal.",
        "opening_hours": "Todos los días: 10-23h (abr-sep) / 10-22:30h (oct-mar)",
        "closed_days": "1 enero, 1 mayo, 8 mayo (mañana), 14 julio (mañana), 11 noviembre (mañana), 25 diciembre",
        "price": "€13 adultos / Gratuito menores 18 y ciudadanos UE menores 26 — ver paris-arc-de-triomphe.fr",
        "currency": "EUR",
        "address": "Place Charles de Gaulle, 75008 Paris",
        "contact": "paris-arc-de-triomphe.fr",
        "official_website": "https://www.paris-arc-de-triomphe.fr",
        "source": "https://www.paris-arc-de-triomphe.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Sacré-Cœur de Montmartre",
        "place_slug": "sacre_coeur_paris",
        "category": "Basílica / Mirador / Barrio Artístico",
        "description": "La basílica blanca sobre la colina más alta de París (130 m). Vista panorámica de toda la ciudad desde la explanada — la más popular y gratuita de París. El barrio de Montmartre que la rodea es el más romántico y pintoresco: Place du Tertre (artistas pintando en vivo), viñedo histórico, molinos (Moulin de la Galette), cabarés históricos (Moulin Rouge está al pie). El funicular (mismo precio que el metro, ~€1,73) o las escaleras (300 peldaños) llevan a la basílica. Interior de la cúpula: €8. Atardecer desde las escaleras: sin precio.",
        "opening_hours": "Basílica: todos los días 6-22:30h | Cúpula: 9:30-17h (invierno) / 9:30-20h (verano)",
        "closed_days": "Ninguno",
        "price": "Basílica: Gratuita | Cúpula: €8 | Funicular: ~€1,73 (billete metro)",
        "currency": "EUR",
        "address": "35 Rue du Chevalier de la Barre, 75018 Paris (Montmartre)",
        "contact": "sacre-coeur-montmartre.com",
        "official_website": "https://www.sacre-coeur-montmartre.com",
        "source": "https://www.sacre-coeur-montmartre.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Sainte-Chapelle",
        "place_slug": "sainte_chapelle_paris",
        "category": "Capilla / Vidrieras Góticas / Patrimonio",
        "description": "La joya gótica más perfecta de París y posiblemente del mundo. Construida por Luis IX (San Luis) en solo 7 años (1242-1248) para albergar la Corona de Espinas de Cristo. La capilla alta tiene 15 vidrieras de 15 metros de altura que cubren el 75% de las paredes — cuando el sol entra, el espacio se convierte en un caleidoscopio de luz coloreada. Considerada el pináculo del arte gótico francés. Pequeña (solo 36x17 m) pero absolutamente impresionante. Comprar online para evitar colas. A 2 min de Notre-Dame.",
        "opening_hours": "Todos los días: 9-17h (oct-mar) / 9-19h (abr-sep)",
        "closed_days": "1 enero, 1 mayo, 25 diciembre",
        "price": "€13 adultos / Gratuito menores 18 y ciudadanos UE menores 26 — ver sainte-chapelle.fr",
        "currency": "EUR",
        "address": "8 Bd du Palais, 75001 Paris (Île de la Cité)",
        "contact": "sainte-chapelle.fr",
        "official_website": "https://www.sainte-chapelle.fr",
        "source": "https://www.sainte-chapelle.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Palais Royal y Jardins du Palais Royal",
        "place_slug": "palais_royal_paris",
        "category": "Jardín Histórico / Columnas de Buren / Galerías",
        "description": "Antiguo palacio del Cardenal Richelieu (1629), hoy sede del Consejo de Estado. El jardín interior es un oasis de paz en el centro de París — completamente gratuito y muy parisino (locales leyendo, niños jugando). Las famosas columnas de Daniel Buren (1986, rayas blancas y negras) llenan el patio de honor y son omnipresentes en Instagram. Las galerías cubiertas que rodean el jardín tienen anticuarios, tiendas de lujo y el restaurante Le Grand Véfour (fundado en 1784). A 2 min del Louvre.",
        "opening_hours": "Jardines: abr-may 7-22:15h / jun-ago 7-23h / sep 7-21:30h / oct-mar 7:30-20:30h",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "EUR",
        "address": "8 Rue de Montpensier, 75001 Paris",
        "contact": "domaine-palais-royal.fr",
        "official_website": "https://www.domaine-palais-royal.fr",
        "source": "https://www.domaine-palais-royal.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── MUSEOS ────────────────────────────────────────────────────────────────
    {
        "name": "Musée du Louvre",
        "place_slug": "louvre_paris",
        "category": "Museo / Arte / El más grande del mundo",
        "description": "El museo más visitado del mundo (9 millones de visitantes/año) y el más grande (73.000 m² de exposición, 35.000 obras a la vista de un total de 550.000). Obras maestras absolutas: La Gioconda (Mona Lisa) de Leonardo da Vinci, La Victoria de Samotracia, La Venus de Milo, Las Bodas de Caná de Veronese, La Balsa de la Medusa de Géricault. La pirámide de cristal de I.M. Pei (1989) es la entrada principal. Imposible ver todo en un día — elegir 2-3 alas. Gratuito el primer viernes del mes a partir de las 18h para menores de 26 años. Los viernes el museo abre hasta las 21:45h.",
        "opening_hours": "Lun, jue, sáb-dom: 9-18h | Mié y vie: 9-21:45h",
        "closed_days": "Martes, 1 enero, 1 mayo, 25 diciembre",
        "price": "€22 adultos / Gratuito menores 18 y ciudadanos UE menores 26 / 1er sáb mes gratuito para todos — ver louvre.fr",
        "currency": "EUR",
        "address": "Rue de Rivoli, 75001 Paris (Pyramide du Louvre)",
        "contact": "louvre.fr | Tel: +33 1 40 20 53 17",
        "official_website": "https://www.louvre.fr",
        "source": "https://www.louvre.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Musée d'Orsay",
        "place_slug": "orsay_paris",
        "category": "Museo / Impresionismo / Arte del siglo XIX",
        "description": "El mejor museo de impresionismo del mundo, alojado en una antigua estación de tren (Gare d'Orsay, 1900). Colección del período 1848-1914: Monet (series de los nenúfares y la Catedral de Rouen), Renoir, Degas, Manet (Olympia, El desayuno sobre la hierba), Van Gogh (La habitación en Arlés, La iglesia de Auvers), Cézanne, Gauguin, Seurat. El reloj de la estación sobre la nave central es uno de los iconos de París. Mucho menos masificado que el Louvre pero igual de importante para el arte. Gratuito el primer domingo del mes.",
        "opening_hours": "Mar-dom: 9:30-18h | Jue: 9:30-21:45h",
        "closed_days": "Lunes, 1 enero, 1 mayo, 25 diciembre",
        "price": "€16 adultos / Gratuito menores 18 y ciudadanos UE menores 26 / 1er dom mes gratuito para todos — ver musee-orsay.fr",
        "currency": "EUR",
        "address": "1 Rue de la Légion d'Honneur, 75007 Paris",
        "contact": "musee-orsay.fr | Tel: +33 1 40 49 48 14",
        "official_website": "https://www.musee-orsay.fr",
        "source": "https://www.musee-orsay.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Centre Pompidou",
        "place_slug": "pompidou_paris",
        "category": "Museo / Arte Moderno y Contemporáneo / Arquitectura",
        "description": "El mayor museo de arte moderno y contemporáneo de Europa, en un edificio revolucionario (1977, Renzo Piano y Richard Rogers) con toda su estructura mecánica — tuberías, escaleras, conductos de aire — expuesta en el exterior pintada de colores. Colección permanente de más de 100.000 obras del siglo XX y XXI: Kandinsky, Matisse, Léger, Dalí, Duchamp, Warhol, Basquiat. La terraza del último piso tiene una de las mejores vistas de París (gratuita con entrada al museo). El barrio de Beaubourg que lo rodea es animado con artistas callejeros y terrazas de café.",
        "opening_hours": "Mié-lun: 11-21h (jue hasta 23h para exposiciones temporales)",
        "closed_days": "Martes, 1 mayo",
        "price": "€15 adultos / Gratuito menores 18 y ciudadanos UE menores 26 / 1er dom mes gratuito — ver centrepompidou.fr",
        "currency": "EUR",
        "address": "Place Georges-Pompidou, 75004 Paris",
        "contact": "centrepompidou.fr | Tel: +33 1 44 78 12 33",
        "official_website": "https://www.centrepompidou.fr",
        "source": "https://www.centrepompidou.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Musée de l'Orangerie",
        "place_slug": "orangerie_paris",
        "category": "Museo / Monet / Nenúfares",
        "description": "Un museo pequeño con una experiencia única en el mundo: las dos salas ovales con los ocho paneles gigantes de los Nenúfares (Nymphéas) de Claude Monet, pintados entre 1914 y 1926 y donados al estado francés. Monet diseñó personalmente las salas para que la luz natural entrara desde el techo, creando una experiencia casi meditativa. Además: colección Walter-Guillaume con Cézanne, Renoir, Matisse, Picasso, Rousseau y Soutine. El museo más íntimo y emocionalmente poderoso de París. Gratuito el primer domingo del mes.",
        "opening_hours": "Mié-lun: 9-18h",
        "closed_days": "Martes, 1 enero, 14 julio (mañana), 25 diciembre",
        "price": "€12,50 adultos / Gratuito menores 18 / 1er dom mes gratuito para todos — ver musee-orangerie.fr",
        "currency": "EUR",
        "address": "Jardin des Tuileries, Place de la Concorde, 75001 Paris",
        "contact": "musee-orangerie.fr | Tel: +33 1 44 77 80 07",
        "official_website": "https://www.musee-orangerie.fr",
        "source": "https://www.musee-orangerie.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Musée Rodin",
        "place_slug": "rodin_paris",
        "category": "Museo / Escultura / Jardín",
        "description": "El museo dedicado al escultor Auguste Rodin (1840-1917), en el Hôtel Biron donde vivió y trabajó. El jardín es tan importante como el interior: El Pensador (Le Penseur), Los Burgueses de Calais, Las Puertas del Infierno, Balzac — todas las esculturas más famosas de Rodin están aquí. El jardín es uno de los más tranquilos y bellos de París, accesible por solo €4 (sin entrar al museo). El interior tiene La Catedral, El Beso y colecciones de Camille Claudel. A 10 min del Orsay.",
        "opening_hours": "Mar-dom: 10-18:30h",
        "closed_days": "Lunes, 1 enero, 1 mayo, 25 diciembre",
        "price": "€14 adultos / Solo jardín: €4 / Gratuito menores 18 / 1er dom mes gratuito — ver musee-rodin.fr",
        "currency": "EUR",
        "address": "77 Rue de Varenne, 75007 Paris",
        "contact": "musee-rodin.fr | Tel: +33 1 44 18 61 10",
        "official_website": "https://www.musee-rodin.fr",
        "source": "https://www.musee-rodin.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Musée Picasso Paris",
        "place_slug": "picasso_paris",
        "category": "Museo / Arte / Picasso",
        "description": "La mayor colección pública de obras de Pablo Picasso del mundo: 5.000 obras (pinturas, esculturas, grabados, cerámicas) en el Hôtel Salé, un palacete del siglo XVII en el Marais. Única en el mundo porque muchas obras fueron donadas directamente por Picasso y su familia, por lo que incluye piezas nunca puestas a la venta. La cronología abarca toda su vida desde el período azul hasta el cubismo tardío. El propio edificio, con su fachada esculpida, es extraordinario.",
        "opening_hours": "Mar-vie: 10:30-18h | Sáb-dom: 9:30-18h",
        "closed_days": "Lunes, 1 enero, 25 diciembre",
        "price": "€14 adultos / Gratuito menores 18 / 1er dom mes gratuito para todos — ver museepicassoparis.fr",
        "currency": "EUR",
        "address": "5 Rue de Thorigny, 75003 Paris (Le Marais)",
        "contact": "museepicassoparis.fr | Tel: +33 1 85 56 00 36",
        "official_website": "https://www.museepicassoparis.fr",
        "source": "https://www.museepicassoparis.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Catacombes de Paris",
        "place_slug": "catacombes_paris",
        "category": "Monumento Subterráneo / Historia / Experiencia Única",
        "description": "El osario más famoso del mundo: 300 km de túneles bajo París con los restos de aproximadamente 6 millones de personas, organizados artísticamente con cráneos y huesos desde finales del siglo XVIII. Solo 2 km están abiertos al público. Temperatura constante de 14°C. Historia: las canteras de piedra caliza que construyeron París se convirtieron en el siglo XVIII en el cementerio subterráneo de la ciudad. Una experiencia espeluznante e impresionante. RESERVAR ONLINE con mucha antelación — las entradas del día se agotan en minutos.",
        "opening_hours": "Mar-dom: 10-20:30h (último acceso 19:30h)",
        "closed_days": "Lunes, 1 enero, 1 mayo, 25 diciembre",
        "price": "€29 adultos (con reserva online) / €5 reducida — ver catacombes.paris.fr",
        "currency": "EUR",
        "address": "1 Av. du Colonel Henri Rol-Tanguy, 75014 Paris",
        "contact": "catacombes.paris.fr | Tel: +33 1 43 22 47 63",
        "official_website": "https://www.catacombes.paris.fr",
        "source": "https://www.catacombes.paris.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "adultos",
        "has_own_agenda": 0,
    },

    # ── BARRIOS ────────────────────────────────────────────────────────────────
    {
        "name": "Le Marais",
        "place_slug": "marais_paris",
        "category": "Barrio / Historia / Galerías / LGBTQIA+",
        "description": "El barrio más histórico y fashion de París: calles medievales perfectamente conservadas, palacios del siglo XVII (hôtels particuliers), la Place des Vosges (la plaza más antigua de París, 1612), galerías de arte contemporáneo, tiendas de diseño y una activa comunidad LGBTQIA+. El Musée Picasso y el Centre Pompidou están aquí. Rue des Rosiers: el corazón histórico del barrio judío con falafel legendario (L'As du Fallafel — cola habitual los domingos). Los domingos la mayoría de las tiendas abren (raro en París). El barrio que nunca duerme.",
        "opening_hours": "Barrio: siempre | Tiendas: generalmente 11-19h (incluido domingos)",
        "closed_days": "Ninguno",
        "price": "Gratuito (explorar) / Falafel desde €7",
        "currency": "EUR",
        "address": "Rue de Rivoli / Place des Vosges, 75003-75004 Paris",
        "contact": "paris.fr",
        "official_website": "https://www.paris.fr",
        "source": "https://www.paris.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Montmartre",
        "place_slug": "montmartre_paris",
        "category": "Barrio / Arte / Historia Bohemia",
        "description": "La colina de los artistas: vivieron aquí Picasso, Modigliani, Toulouse-Lautrec, Van Gogh, Renoir, Dalí y Utrillo. El barrio más pintoresco de París, con calles empedradas, viñedos urbanos, cabarés históricos y el Sacré-Cœur en la cima. Place du Tertre: artistas pintando retratos y paisajes en vivo. Moulin de la Galette: el molino donde Renoir pintó su obra más famosa. Museo de Montmartre (la antigua residencia de Renoir, Susanne Valadon y otros artistas). El barrio de Pigalle al pie tiene la vida nocturna parisina más clásica.",
        "opening_hours": "Barrio: siempre | Museo de Montmartre: 10-19h (abr-sep) / 10-18h (oct-mar)",
        "closed_days": "Ninguno (Museo: 1 enero y 25 diciembre)",
        "price": "Gratuito (barrio) / Museo de Montmartre: €15",
        "currency": "EUR",
        "address": "Place du Tertre / Rue Lepic, 75018 Paris",
        "contact": "montmartremuseum.com",
        "official_website": "https://www.montmartremuseum.com",
        "source": "https://www.montmartremuseum.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Saint-Germain-des-Prés",
        "place_slug": "saint_germain_paris",
        "category": "Barrio / Intelectual / Cafés Literarios",
        "description": "El barrio intelectual y literario de París por excelencia. En los Cafés de Flore y Les Deux Magots se sentaron Sartre, Beauvoir, Hemingway, Fitzgerald y Camus. La Brasserie Lipp, la librería La Hune y el jazz club Café de la Mairie son hitos del barrio. La Iglesia de Saint-Germain-des-Prés (la más antigua de París, siglo VI) en la plaza del mismo nombre. A 5 minutos a pie del Orsay y a 10 del Louvre. Hoy con muchas boutiques de lujo, pero el ambiente literario e intelectual sigue presente.",
        "opening_hours": "Barrio: siempre | Cafés literarios: desde 7:30h",
        "closed_days": "Ninguno",
        "price": "Gratuito (barrio) / Café en Flore o Deux Magots: €5-8 por consumición",
        "currency": "EUR",
        "address": "Place Saint-Germain-des-Prés, 75006 Paris",
        "contact": "paris.fr",
        "official_website": "https://www.paris.fr",
        "source": "https://www.paris.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Canal Saint-Martin y Belleville",
        "place_slug": "canal_saint_martin_paris",
        "category": "Barrio / Canal / Vida Alternativa",
        "description": "El canal más fotogénico de París (5 km, construido por Napoleón en 1825) con sus puentes de hierro, esclusas y tilos centenarios. Barrio de moda sin ser turístico: cafés independientes, librerías, galerías de arte emergente, restaurantes bio. Los domingos el canal se convierte en zona peatonal con picnics a orillas del agua. Belleville (al norte) es el barrio multicultural más vibrante: comunidad china, árabe y africana conviviendo con artistas y jóvenes creativos. Murales de arte urbano en cada esquina.",
        "opening_hours": "Siempre accesible | Paseo peatonal domingos y festivos",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "EUR",
        "address": "Quai de Jemmapes, 75010 Paris",
        "contact": "paris.fr",
        "official_website": "https://www.paris.fr",
        "source": "https://www.paris.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── PARQUES Y ESPACIOS ────────────────────────────────────────────────────
    {
        "name": "Jardin des Tuileries",
        "place_slug": "tuileries_paris",
        "category": "Jardín / Escultura / Paseo",
        "description": "El jardín más antiguo de París (1564, Catalina de Médici), entre el Louvre y la Place de la Concorde en pleno eje histórico. Esculturas de Rodin, Maillol y otros artistas esparcidas por las avenidas de grava y setos. El estanque octogonal central con sillas de metal verdes donde los parisinos leen y toman el sol. En verano: Fête des Tuileries (feria de atracciones con noria). El Jeu de Paume y el Musée de l'Orangerie están en los extremos del jardín. Uno de los paseos más elegantes y gratuitos de Europa.",
        "opening_hours": "Abr-sep: 7-21h | Jun-ago: 7:30-23h | Oct-mar: 7:30-19:30h",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "EUR",
        "address": "Place de la Concorde, 75001 Paris",
        "contact": "louvre.fr/jardins",
        "official_website": "https://www.louvre.fr/le-palais-et-ses-jardins/les-jardins-des-tuileries",
        "source": "https://www.louvre.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Jardin du Luxembourg",
        "place_slug": "jardin_luxembourg_paris",
        "category": "Jardín / Senado / Actividades",
        "description": "El jardín favorito de los parisinos (23 hectáreas en el Quartier Latin). La Fontaine Médicis (1630), el estanque central donde niños empujan barquitos de madera con palos desde hace siglos, las sillas de hierro verdes a la sombra, el palacio del Senado. Actividades: tenis, pétanque, ajedrez, ping-pong. Pista de jogging de 1,7 km alrededor. Los miércoles hay teatro de Guignol (marionetas) para niños. Ambiente completamente local y parisino — casi sin turistas comparado con las Tullerías. A 5 min del Panteón.",
        "opening_hours": "Varía por estación: generalmente 7:30 o 8:30h al anochecer",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "EUR",
        "address": "Rue de Médicis - Rue de Vaugirard, 75006 Paris",
        "contact": "senat.fr/visite/jardin",
        "official_website": "https://www.senat.fr/visite/jardin/index.html",
        "source": "https://www.senat.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Champs-Élysées y Avenue Montaigne",
        "place_slug": "champs_elysees_paris",
        "category": "Avenida Icónica / Compras / Ocio",
        "description": "La avenida más famosa del mundo: 1,9 km desde la Place de la Concorde hasta el Arc de Triomphe. No es la más cara de compras (eso es Avenue Montaigne) pero sí la más simbólica: Défilé del 14 de julio (desfile militar nacional), llegada del Tour de France, final de la Copa del Mundo 1998. Tiendas de lujo, cines, restaurantes, el Lido. En Navidad: los mejores mercados navideños y la iluminación más espectacular de Europa. La parte más elegante para compras es Avenue Montaigne (Dior, Chanel, Louis Vuitton). Pasear es gratuito.",
        "opening_hours": "Siempre accesible | Tiendas: 10-20h (algunas hasta 22h)",
        "closed_days": "Ninguno",
        "price": "Gratuito (pasear)",
        "currency": "EUR",
        "address": "Avenue des Champs-Élysées, 75008 Paris",
        "contact": "paris.fr",
        "official_website": "https://www.paris.fr",
        "source": "https://www.paris.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── ESPECTÁCULOS / EXPERIENCIAS ───────────────────────────────────────────
    {
        "name": "Opéra Garnier (Palais Garnier)",
        "place_slug": "opera_garnier_paris",
        "category": "Ópera / Ballet / Arquitectura Napoleónica",
        "description": "Uno de los edificios más suntuosos del mundo (1875, Charles Garnier). Interior deslumbrante: la gran escalera de mármol, la sala con la araña de cristal de 6 toneladas (real, no del Fantasma de la Ópera), el techo pintado por Chagall en 1964. Sede de la Ópera Nacional de París junto con la Ópera Bastille. Las visitas guiadas al interior son extraordinarias incluso sin ver un espectáculo. Ubicado en uno de los barrios más elegantes: Grands Boulevards, Galeries Lafayette a 2 minutos.",
        "opening_hours": "Visitas: 10-17h (no en días de ensayo general) | Espectáculos: ver operadeparis.fr",
        "closed_days": "Variable según función",
        "price": "Visita: €14 adultos / €10 reducida | Ópera/Ballet: desde €15 (galería) a €230 — ver operadeparis.fr",
        "currency": "EUR",
        "address": "Place de l'Opéra, 75009 Paris",
        "contact": "operadeparis.fr | Tel: +33 1 71 25 24 23",
        "official_website": "https://www.operadeparis.fr",
        "source": "https://www.operadeparis.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Moulin Rouge",
        "place_slug": "moulin_rouge_paris",
        "category": "Cabaret / Espectáculo / Icono Cultural",
        "description": "El cabaret más famoso del mundo (1889). Inventó el can-can y fue frecuentado por Toulouse-Lautrec, que lo inmortalizó en sus carteles. El espectáculo Féerie lleva en cartel más de 30 años: 60 artistas, 1.000 plumas, lentejuelas y el famoso can-can final. El molino rojo en el exterior es uno de los iconos de París. No es barato pero es una experiencia única. Alternativa más económica: ver solo el exterior (gratis) en la Rue Lepic, al pie de Montmartre — el barrio Pigalle que lo rodea tiene bares y clubs para todos los gustos.",
        "opening_hours": "Shows: cena 19h / Shows 21h y 23h (sin cena)",
        "closed_days": "Ninguno",
        "price": "Show 21h o 23h: desde €120 por persona (con media botella de champán) | Cena+Show: desde €230 — ver moulinrouge.fr",
        "currency": "EUR",
        "address": "82 Boulevard de Clichy, 75018 Paris (Pigalle)",
        "contact": "moulinrouge.fr | Tel: +33 1 53 09 82 82",
        "official_website": "https://www.moulinrouge.fr",
        "source": "https://www.moulinrouge.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "adultos",
        "has_own_agenda": 1,
    },
    {
        "name": "Croisière en Seine — Bateaux Parisiens / Bateaux Mouches",
        "place_slug": "crucero_seine_paris",
        "category": "Crucero / Panorámica / Experiencia",
        "description": "Un crucero por el río Sena permite ver en 1 hora los monumentos más importantes de París desde el agua: Torre Eiffel, Notre-Dame, el Louvre, el Orsay, la Conciergerie, el Instituto de Francia y los puentes históricos. Hay dos operadores principales: Bateaux Mouches (salida desde el Pont de l'Alma) y Bateaux Parisiens (salida desde la Torre Eiffel). Ambos incluyen audio en varios idiomas. Por la noche el crucero es especialmente mágico con los monumentos iluminados. Crucero Vedettes du Pont Neuf es algo más barato.",
        "opening_hours": "Todo el año: cada 30-45 min desde las 10:30h hasta las 22:30h (verano hasta 23h)",
        "closed_days": "Ninguno",
        "price": "€17-19 adultos / €8-10 niños — ver bateaux-parisiens.com o bateaux-mouches.fr",
        "currency": "EUR",
        "address": "Port de la Bourdonnais (Bateaux Parisiens) / Pont de l'Alma (Bateaux Mouches), 75007 Paris",
        "contact": "bateaux-parisiens.com | bateaux-mouches.fr",
        "official_website": "https://www.bateaux-parisiens.com",
        "source": "https://www.bateaux-parisiens.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Versailles — Palacio y Jardines",
        "place_slug": "versailles_paris",
        "category": "Excursión / Palacio Real / Jardines UNESCO",
        "description": "La excursión de un día más importante desde París (30 min en RER C desde Saint-Michel). El Palacio de Versailles fue la residencia de los reyes de Francia desde Luis XIV hasta la Revolución Francesa (1682-1789). Interior: la Galería de los Espejos (73 m con 357 espejos), los aposentos del Rey, los salones de estado. Jardines de Le Nôtre: 800 hectáreas de geometría perfecta con fuentes musicales (sábados y domingos de abr a oct). El Trianón (palacete más íntimo) y el Hameau de la Reine (aldea campestre de María Antonieta) requieren tiempo adicional. Llegar antes de las 9:30h para evitar colas.",
        "opening_hours": "Mar-dom: 9-18:30h (nov-mar: 9-17:30h) | Jardines: abr-oct 8-20:30h, nov-mar 8-18h",
        "closed_days": "Lunes, 1 enero, 25 diciembre",
        "price": "Palacio: €21 adultos / Gratuito menores 18 / Jardines: gratuito (excepto días de fuentes: €10) — ver chateauversailles.fr",
        "currency": "EUR",
        "address": "Place d'Armes, 78000 Versailles (RER C: Versailles-Château-Rive-Gauche)",
        "contact": "chateauversailles.fr | Tel: +33 1 30 83 78 00",
        "official_website": "https://www.chateauversailles.fr",
        "source": "https://www.chateauversailles.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Marché d'Aligre",
        "place_slug": "marche_aligre_paris",
        "category": "Mercado / Gastronomía / Vida Local",
        "description": "El mercado más auténtico y barato de París — todavía no descubierto masivamente por el turismo. Tres partes: mercado al aire libre (frutas, verduras, especias, aceitunas — precios por debajo de los supermercados), mercado cubierto Beauvau (carnes, quesos, vinos, flores), y el mercado de pulgas con ropa vintage y antigüedades. Ambiente completamente local: los comerciantes regatean, los parisinos del barrio discuten sobre política. El bar Le Baron Rouge frente al mercado tiene vino natural desde €3 la copa — los domingos se sientan en la calle sobre barriles.",
        "opening_hours": "Mar-sáb: 8-13h y 16-19:30h | Dom: 8-13h | Mercado pulgas: mar-dom 8-13h",
        "closed_days": "Lunes",
        "price": "Gratuito (entrar) / Productos desde €1",
        "currency": "EUR",
        "address": "Place d'Aligre, 75012 Paris",
        "contact": "paris.fr",
        "official_website": "https://www.paris.fr",
        "source": "https://www.paris.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Panthéon de Paris",
        "place_slug": "pantheon_paris",
        "category": "Monumento / Panteón / Historia de Francia",
        "description": "El mausoleo laico de los grandes hombres y mujeres de Francia. En las criptas descansan: Voltaire, Rousseau, Victor Hugo, Émile Zola, Marie Curie (la única mujer), Louis Braille, Jean Jaurès, Jean Moulin, Simone Veil. La cúpula neoclásica domina el Barrio Latino. El péndulo de Foucault original (1851) demuestra la rotación de la Tierra en la nave central. La terraza (acceso adicional) da vistas extraordinarias del Barrio Latino. El edificio fue construido como iglesia pero la Revolución lo convirtió en monumento nacional.",
        "opening_hours": "Todos los días: 10-18:30h (oct-mar: 10-18h)",
        "closed_days": "1 enero, 1 mayo, 25 diciembre",
        "price": "€13 adultos / Gratuito menores 18 y ciudadanos UE menores 26 — ver paris-pantheon.fr",
        "currency": "EUR",
        "address": "Place du Panthéon, 75005 Paris (Quartier Latin)",
        "contact": "paris-pantheon.fr | Tel: +33 1 44 32 18 00",
        "official_website": "https://www.paris-pantheon.fr",
        "source": "https://www.paris-pantheon.fr",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Marché aux Puces de Saint-Ouen (Clignancourt)",
        "place_slug": "puces_saint_ouen_paris",
        "category": "Mercado de Antigüedades / Vintage / Fin de semana",
        "description": "El mercado de antigüedades más grande del mundo: 15 mercados internos con 2.500 anticuarios y 80.000 m² en Saint-Ouen, al norte de París (Porte de Clignancourt). Todo a la venta: muebles Luis XV, posters vintage, ropa de los años 60, joyería art déco, lámparas, discos de vinilo, arte, fotografías históricas. El mercado Malik es el más accesible; el Paul Bert, el más lujoso. Negociar precios es habitual y esperado. Restaurantes de Senegal y África Occidental en los alrededores. Una experiencia de un día completo.",
        "opening_hours": "Sáb: 9-18h | Dom: 10-18h | Lun: 11-17h",
        "closed_days": "Mar-vie",
        "price": "Gratuito (entrar) / Compras a partir de €5",
        "currency": "EUR",
        "address": "Rue des Rosiers, 93400 Saint-Ouen (Metro: Porte de Clignancourt, línea 4)",
        "contact": "marcheauxpuces-saintouen.com",
        "official_website": "https://www.marcheauxpuces-saintouen.com",
        "source": "https://www.marcheauxpuces-saintouen.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
]


def import_static_places_paris():
    print(f"\nImportando {len(PLACES)} lugares estáticos de París...")
    init_db()
    city_id = get_or_create_city("París", "Francia")

    for place in PLACES:
        insert_place(city_id, place)

    print(f"\nImportacion completada: {len(PLACES)} lugares de París")


if __name__ == "__main__":
    import_static_places_paris()
