"""
Importador de lugares estáticos de Madrid.
Cubre museos, barrios, parques, mercados, teatros y experiencias icónicas.
Moneda: EUR.
"""
import sys, os
from datetime import date
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from db.database import init_db, get_or_create_city, insert_place

TODAY = date.today().isoformat()

PLACES = [

    # ── MUSEOS DEL TRIÁNGULO DEL ARTE ─────────────────────────────────────────
    {
        "name": "Museo Nacional del Prado",
        "place_slug": "prado_madrid",
        "category": "Museo / Arte Clásico / Patrimonio",
        "description": "El museo más importante de España y uno de los más grandes del mundo. 8.000 obras en exposición de 7.600 artistas. Velázquez (Las Meninas), Goya (Saturno devorando a su hijo, La maja desnuda), El Bosco (El jardín de las delicias), Rubens, Tiziano, Rafael. La colección de Velázquez es la más completa del mundo. Entrada gratuita lunes a sábados 18-20h y domingos 17-19h. Cola habitual de 30-45 min en horario gratuito — llegar con antelación o comprar online.",
        "opening_hours": "Lun-sáb: 10-20h | Dom y festivos: 10-19h | Gratis: lun-sáb 18-20h, dom 17-19h",
        "closed_days": "1 enero, 1 mayo, 25 diciembre",
        "price": "€15 adultos / €7,50 reducida / Gratuito últimas 2h - ver museodelprado.es",
        "currency": "EUR",
        "address": "Calle Ruiz de Alarcón 23, Retiro, Madrid",
        "contact": "museodelprado.es | Tel: +34 913 302 800",
        "official_website": "https://www.museodelprado.es",
        "source": "https://www.museodelprado.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Museo Nacional Centro de Arte Reina Sofía",
        "place_slug": "reina_sofia_madrid",
        "category": "Museo / Arte Moderno y Contemporáneo",
        "description": "El museo de arte moderno y contemporáneo más importante de España. Alberga el Guernica de Picasso — la obra más poderosa del siglo XX sobre la guerra, pintada en 1937 en respuesta al bombardeo de la ciudad vasca. También obras de Salvador Dalí, Joan Miró, Juan Gris, Julio González. El edificio original (antiguo Hospital General del siglo XVIII) y la ampliación de Jean Nouvel (2005). Gratuito lunes, miércoles a sábados 19-21h y domingos 12:30-14:30h.",
        "opening_hours": "Lun, mié-sáb: 10-21h | Dom: 10-14:30h | Mar: cerrado | Gratis: lun y mié-sáb 19-21h, dom 12:30-14:30h",
        "closed_days": "Martes, 1 enero, 25 diciembre",
        "price": "€12 adultos / Gratuito menores 18, mayores 65, desempleados - ver museoreinasofia.es",
        "currency": "EUR",
        "address": "Calle Santa Isabel 52, Lavapiés, Madrid",
        "contact": "museoreinasofia.es | Tel: +34 917 741 000",
        "official_website": "https://www.museoreinasofia.es",
        "source": "https://www.museoreinasofia.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Museo Thyssen-Bornemisza",
        "place_slug": "thyssen_madrid",
        "category": "Museo / Arte / Colección Privada",
        "description": "El tercer vértice del Triángulo del Arte madrileño. Colección enciclopédica que cubre 7 siglos de historia del arte: desde los primitivos flamencos hasta el arte pop americano. Ideal para ver el arte que no está en el Prado ni en el Reina Sofía: impresionismo (Monet, Degas, Renoir), expresionismo, surrealismo. Único de los tres que NO tiene entrada gratuita regular, pero los lunes la colección permanente es gratis.",
        "opening_hours": "Mar-vie: 10-19h | Sáb: 10-21h | Dom y lun: 10-19h",
        "closed_days": "1 enero, 25 diciembre",
        "price": "€13 adultos / €9 reducida / Gratuito lunes (colección permanente) - ver museothyssen.org",
        "currency": "EUR",
        "address": "Paseo del Prado 8, Retiro, Madrid",
        "contact": "museothyssen.org | Tel: +34 917 911 370",
        "official_website": "https://www.museothyssen.org",
        "source": "https://www.museothyssen.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },

    # ── MONUMENTOS / ESPACIOS ICÓNICOS ────────────────────────────────────────
    {
        "name": "Parque del Buen Retiro",
        "place_slug": "retiro_madrid",
        "category": "Parque / Patrimonio UNESCO / Naturaleza",
        "description": "El pulmón verde de Madrid (declarado Patrimonio de la Humanidad UNESCO en 2021 junto al Paseo del Prado). 118 hectáreas en pleno centro con lago (alquiler de barcas: €6/45 min), Palacio de Cristal (exposiciones gratuitas), Palacio de Velázquez (exposiciones), Fuente del Ángel Caído (único monumento al diablo en el mundo), jardín de la Rosaleda, esculturas. Lleno de madrileños haciendo deporte, leyendo y tomando el sol. Los domingos hay músicos callejeros y actuaciones espontáneas. Totalmente gratuito.",
        "opening_hours": "Abr-oct: 6-24h | Nov-mar: 6-22h",
        "closed_days": "Nenhum",
        "price": "Gratuito / Barcas lago: €6 por 45 min",
        "currency": "EUR",
        "address": "Plaza de la Independencia 7, Retiro, Madrid",
        "contact": "madrid.es/retiro",
        "official_website": "https://www.madrid.es/portales/munimadrid/es/Inicio/El-Ayuntamiento/Parques-y-jardines",
        "source": "https://www.madrid.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Palacio Real de Madrid",
        "place_slug": "palacio_real_madrid",
        "category": "Palacio / Patrimonio Histórico / Monarquía",
        "description": "La residencia oficial de la Familia Real Española (aunque los reyes no viven aquí habitualmente). El palacio más grande de Europa Occidental: 135.000 m², 3.418 habitaciones. Construcción del siglo XVIII sobre el antiguo Alcázar árabe. Interior suntuoso: Salón del Trono, Sala de Porcelana, armería real con armaduras medievales, colecciones de arte con obras de Velázquez, Caravaggio y Goya. Cambio de guardia los miércoles y sábados a las 11h (gratuito ver desde exterior). Los Jardines de Sabatini (frente al palacio) son gratuitos.",
        "opening_hours": "Abr-sep: 10-20h | Oct-mar: 10-18h (últimas entradas 1h antes)",
        "closed_days": "Días de actos oficiales de la Familia Real (verificar web)",
        "price": "€14 adultos / €7 reducida / Gratuito lun-jue 17-20h (abr-sep) o 16-18h (oct-mar) para ciudadanos UE - ver patrimonionacional.es",
        "currency": "EUR",
        "address": "Calle Bailén s/n, Palacio, Madrid",
        "contact": "patrimonionacional.es | Tel: +34 914 548 700",
        "official_website": "https://www.patrimonionacional.es/visita/palacio-real-de-madrid",
        "source": "https://www.patrimonionacional.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Plaza Mayor de Madrid",
        "place_slug": "plaza_mayor_madrid",
        "category": "Plaza Histórica / Patrimonio / Vida Urbana",
        "description": "El corazón histórico de Madrid (siglo XVII). 237 x 129 metros rodeados de edificios uniformes con 237 balcones. Estatua ecuestre de Felipe III en el centro. Fue escenario de corridas de toros, autos de fe de la Inquisición, mercados y coronaciones reales. Hoy: restaurantes con terrazas (caros pero el ambiente vale), tiendas de souvenirs, artistas callejeros y el famoso Mercado de Navidad en diciembre. Punto de partida ideal para explorar el Madrid histórico: La Latina, Puerta del Sol y Calle Mayor a pie.",
        "opening_hours": "Siempre accesible (plaza abierta 24h)",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "EUR",
        "address": "Plaza Mayor s/n, Centro, Madrid",
        "contact": "esmadrid.com",
        "official_website": "https://www.esmadrid.com/informacion-turistica/plaza-mayor",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Puerta del Sol",
        "place_slug": "puerta_sol_madrid",
        "category": "Plaza / Kilómetro 0 / Centro Neurálgico",
        "description": "El centro geográfico de España (Kilómetro 0 de las carreteras radiales) y el corazón palpitante de Madrid. La estatua del Oso y el Madroño es el símbolo de la ciudad y punto de encuentro universal. Nochevieja: 50.000 personas se reúnen para las 12 uvas al ritmo de los campanazos del reloj. La plaza está rodeada de las calles comerciales principales: Preciados, Arenal, Montera. Metro: 3 líneas confluyen aquí. Funciona como orientación: todo Madrid se mide desde aquí.",
        "opening_hours": "Siempre accesible (24h)",
        "closed_days": "Ninguno",
        "price": "Gratuito",
        "currency": "EUR",
        "address": "Puerta del Sol s/n, Centro, Madrid",
        "contact": "esmadrid.com",
        "official_website": "https://www.esmadrid.com",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Templo de Debod",
        "place_slug": "templo_debod_madrid",
        "category": "Monumento / Templo Egipcio / Mirante",
        "description": "Un templo egipcio auténtico del siglo II a.C. trasladado piedra por piedra desde Egipto a Madrid en 1968 como agradecimiento por la ayuda española en el salvamento de los templos de Nubia. Completamente fuera de lugar y por eso fascinante: un templo faraónico en pleno parque del Oeste madrileño. La puesta de sol desde aquí, con el templo reflejado en el estanque y la Casa de Campo de fondo, es uno de los espectáculos gratuitos más impresionantes de Madrid. Filas en verano al atardecer.",
        "opening_hours": "Mar-vie: 10-14h y 18-20h (oct-mar 16-18h) | Sáb-dom: 10-14h y 18-20h",
        "closed_days": "Lunes, 1 enero, 24-25 diciembre, 31 diciembre",
        "price": "Gratuito",
        "currency": "EUR",
        "address": "Calle Ferraz 1, Parque del Oeste, Madrid",
        "contact": "madrid.es",
        "official_website": "https://www.madrid.es/portales/munimadrid/es/Inicio/Cultura-ocio-y-deporte/Arte-y-cultura/Museos/Templo-de-Debod",
        "source": "https://www.madrid.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Gran Vía de Madrid",
        "place_slug": "gran_via_madrid",
        "category": "Avenida Icónica / Arquitectura / Compras / Teatro",
        "description": "El 'Broadway madrileño': 1,3 km de avenida construida entre 1910 y 1933, con edificios art déco y ecléticos de enorme valor arquitectónico (Edificio Metrópolis, Edificio Telefónica, Hotel Gran Vía). Concentra los teatros más importantes de Madrid (musicals, comedias), cines históricos, tiendas internacionales y restaurantes. Por la noche, la iluminación y el ambiente son únicos. El mirador del Círculo de Bellas Artes (€5) al final de la calle ofrece la mejor vista aérea de la Gran Vía.",
        "opening_hours": "Siempre accesible | Tiendas: generalmente 10-22h | Teatros: consultar cartelera",
        "closed_days": "Ninguno",
        "price": "Gratuito (pasear) / Círculo de Bellas Artes terraza: €5",
        "currency": "EUR",
        "address": "Gran Vía s/n, Centro, Madrid",
        "contact": "esmadrid.com",
        "official_website": "https://www.esmadrid.com",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── BARRIOS ICÓNICOS ──────────────────────────────────────────────────────
    {
        "name": "La Latina y El Rastro",
        "place_slug": "la_latina_madrid",
        "category": "Barrio / Tapas / Mercado de Antigüedades",
        "description": "La Latina es el barrio más castizo (auténtico) de Madrid: calles medievales, tabernas centenarias y la mejor ruta de tapas de la ciudad. La Cava Baja es la calle más famosa para tapear: Txirimiri, El Almendro 13, Casa Lucio. El Rastro: el mercado de segunda mano y antigüedades más famoso de España, cada domingo de 9h a 15h en la Calle Ribera de Curtidores y alrededores (más de 3.500 puestos). Después del Rastro, los domingos, toda La Latina se llena para el vermut y las tapas.",
        "opening_hours": "Barrio: siempre | Tapas: 13-16h y 20-24h | El Rastro: domingos 9-15h",
        "closed_days": "Ninguno (El Rastro solo domingos y festivos)",
        "price": "Gratuito (barrio y Rastro) / Tapas desde €2",
        "currency": "EUR",
        "address": "Calle Cava Baja s/n / Plaza de Cascorro (El Rastro), La Latina, Madrid",
        "contact": "esmadrid.com",
        "official_website": "https://www.esmadrid.com/informacion-turistica/el-rastro",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Malasaña y Chueca",
        "place_slug": "malasana_chueca_madrid",
        "category": "Barrios / Vida Nocturna / Cultura Alternativa",
        "description": "Los dos barrios más vibrantes y modernos de Madrid. Malasaña: epicentro de la movida madrileña de los 80, hoy hipster y alternativo — tiendas vintage, bares con música en directo, cafés con encanto en la Plaza del Dos de Mayo. Chueca: el barrio LGBTQIA+ por excelencia, colorido, festivo y con restaurantes de todas las cocinas del mundo. La calle Fuencarral conecta ambos barrios con tiendas independientes. Por la noche, ambos barrios son el motor de la vida nocturna madrileña.",
        "opening_hours": "Barrios: siempre | Bares: desde las 20h (mejor desde las 22h) | Tiendas: 10-21h",
        "closed_days": "Ninguno",
        "price": "Gratuito (explorar) / Copas desde €4",
        "currency": "EUR",
        "address": "Plaza del Dos de Mayo (Malasaña) / Calle Hortaleza (Chueca), Madrid",
        "contact": "esmadrid.com",
        "official_website": "https://www.esmadrid.com",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "adultos",
        "has_own_agenda": 0,
    },
    {
        "name": "Barrio de las Letras (Huertas)",
        "place_slug": "barrio_letras_madrid",
        "category": "Barrio / Literatura / Tapas / Flamenco",
        "description": "El barrio literario de Madrid: vivieron aquí Cervantes, Lope de Vega, Quevedo y Góngora en los siglos XVI-XVII. Las calles tienen frases de sus obras incrustadas en el suelo. Casa natal de Lope de Vega (museo, €2). Calle Huertas: el corazón de la vida nocturna del centro con bares de vino y tablaos flamencos. Muy cerca del Paseo del Prado (5 min a pie a los tres museos). Teatro Español en la Plaza de Santa Ana. Ambiente cervecero y cultural mezclado.",
        "opening_hours": "Barrio: siempre | Bares: desde 20h | Tablaos flamenco: desde 21h",
        "closed_days": "Ninguno",
        "price": "Gratuito (explorar) / Tablao flamenco: €35-70 con bebida",
        "currency": "EUR",
        "address": "Calle Huertas s/n / Plaza de Santa Ana, Centro, Madrid",
        "contact": "esmadrid.com",
        "official_website": "https://www.esmadrid.com",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Lavapiés",
        "place_slug": "lavapies_madrid",
        "category": "Barrio / Multicultural / Arte / Gastronomía",
        "description": "El barrio más multicultural de Madrid: conviven comunidades india, marroquí, senegalesa, bangladesí y china junto a artistas, estudiantes y familias de toda la vida. Restaurantes auténticos de todo el mundo a precios bajos. El Mercado de Antón Martín (con bares de pintxos vascos y japoneses). La Filmoteca Española (películas de autor baratas). Tabacalera: antigua fábrica de tabaco convertida en centro de arte urbano gratuito. Mucho arte callejero. Ambiente bohemio con toque canalla.",
        "opening_hours": "Barrio: siempre | Filmoteca: mar-dom desde 17h | Tabacalera: horario variable",
        "closed_days": "Ninguno (barrio)",
        "price": "Gratuito (explorar) / Comida desde €5 / Filmoteca €3",
        "currency": "EUR",
        "address": "Plaza de Lavapiés s/n, Embajadores, Madrid",
        "contact": "esmadrid.com",
        "official_website": "https://www.esmadrid.com",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── GASTRONOMÍA / MERCADOS ────────────────────────────────────────────────
    {
        "name": "Mercado de San Miguel",
        "place_slug": "mercado_san_miguel_madrid",
        "category": "Mercado Gourmet / Gastronomía",
        "description": "El mercado gastronómico más famoso de Madrid (1916, estructura de hierro art nouveau). 33 puestos con lo mejor de la gastronomía española: jamón ibérico, ostras, anchoas, vinos, cervezas artesanales, croquetas, pintxos vascos y dulces tradicionales. Muy turístico y por tanto caro (una copa de vino €4-6, una ración de jamón €8-15), pero el ambiente y la arquitectura del edificio valen la visita. Lleno a todas horas. A 2 min de la Plaza Mayor.",
        "opening_hours": "Dom-mié: 10-24h | Jue-sáb: 10-01h",
        "closed_days": "Ninguno",
        "price": "Gratuito (entrar) / Consumiciones desde €2 / Raciones €5-20",
        "currency": "EUR",
        "address": "Plaza de San Miguel s/n, Centro, Madrid",
        "contact": "mercadodesanmiguel.es | Tel: +34 915 424 936",
        "official_website": "https://www.mercadodesanmiguel.es",
        "source": "https://www.mercadodesanmiguel.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "San Isidro y Verbenas Populares de Madrid",
        "place_slug": "fiestas_madrid",
        "category": "Fiestas Populares / Cultura / Chotis",
        "description": "Las fiestas de San Isidro (15 de mayo, patrón de Madrid) son las más importantes de la ciudad: conciertos gratuitos, verbenas populares, chotis en la Pradera de San Isidro. La ermita de San Isidro en la colina del mismo nombre es el punto de peregrinación. En verano: verbenas de La Paloma (agosto) y La Virgen de la Almudena (noviembre). El Recinto Ferial de la Casa de Campo acoge ferias, conciertos y Mad Cool Festival en julio.",
        "opening_hours": "Fiestas San Isidro: semana del 15 mayo | Verbenas: agosto",
        "closed_days": "Variable por temporada",
        "price": "Gratuito (verbenas y acceso) / Algunos conciertos con entrada",
        "currency": "EUR",
        "address": "Pradera de San Isidro / Casa de Campo, Madrid",
        "contact": "esmadrid.com/fiestasanisidro",
        "official_website": "https://www.esmadrid.com/informacion-turistica/fiestas-de-san-isidro",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },

    # ── TEATROS / ESPECTÁCULOS ────────────────────────────────────────────────
    {
        "name": "Teatro Real de Madrid",
        "place_slug": "teatro_real_madrid",
        "category": "Ópera / Ballet / Música Clásica",
        "description": "El principal teatro de ópera de España y uno de los más prestigiosos de Europa. Inaugurado en 1850, restaurado en 1997. Temporada de ópera y ballet de octubre a julio con produciones internacionales de alto nivel. Visitas guiadas al interior (platea, camarines, tramoya). La plaza de Oriente frente al teatro, con el Palacio Real de fondo, es una de las mejores vistas de Madrid. El Café de Oriente en la plaza tiene una de las mejores terrazas del centro.",
        "opening_hours": "Visitas: según temporada, generalmente 10:30-13h | Espectáculos: ver temporada en teatro-real.com",
        "closed_days": "Variable según función",
        "price": "Visita guiada: €8 adultos / €5 reducida | Entradas ópera: desde €10 (anfiteatro) a €300 (palcos) - ver teatro-real.com",
        "currency": "EUR",
        "address": "Plaza de Oriente s/n, Palacio, Madrid",
        "contact": "teatro-real.com | Tel: +34 902 244 848",
        "official_website": "https://www.teatro-real.com",
        "source": "https://www.teatro-real.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "adultos",
        "has_own_agenda": 1,
    },
    {
        "name": "Teatros del Canal",
        "place_slug": "teatros_canal_madrid",
        "category": "Teatro / Danza / Artes Escénicas",
        "description": "El mayor complejo de artes escénicas de Madrid (2009): 4 salas con capacidades de 100 a 1.500 personas. Programación ecléctica de calidad: danza contemporánea, teatro, circo, música. Sede habitual de la Compañía Nacional de Danza y producciones internacionales. Muchas funciones de martes a domingo. Zona Chamberí, a 10 min del Bernabéu.",
        "opening_hours": "Taquilla: lun-sáb 11-20h | Funciones: mar-dom (ver programación)",
        "closed_days": "Lunes (funciones)",
        "price": "Desde €6 a €35 según espectáculo - ver teatroscanal.com",
        "currency": "EUR",
        "address": "Calle Cea Bermúdez 1, Chamberí, Madrid",
        "contact": "teatroscanal.com | Tel: +34 913 083 990",
        "official_website": "https://www.teatroscanal.com",
        "source": "https://www.teatroscanal.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Círculo de Bellas Artes de Madrid",
        "place_slug": "circulo_bellas_artes_madrid",
        "category": "Centro Cultural / Terraza / Arte",
        "description": "Centro cultural histórico (1926) en plena Gran Vía. Programación variada: exposiciones de arte, ciclos de cine, conferencias, baile, teatro. La joya es la terraza Azotea (planta 7): la mejor vista de Madrid desde las alturas, con bar incluido. Icónica la estatua de Minerva en la cubierta. El interior modernista con la sala principal (Salón de Baile) es impresionante. Carnet de socio por €2 al día da acceso a la terraza y al interior.",
        "opening_hours": "Centro: según actividad | Azotea (terraza): 11-02h (verano) / 11-24h (invierno)",
        "closed_days": "Ninguno",
        "price": "Carnet día: €4 (incluye terraza) / Exposiciones: €4-6 / Terraza + bebida ~€10",
        "currency": "EUR",
        "address": "Calle de Alcalá 42, Centro, Madrid",
        "contact": "circulobellasartes.com | Tel: +34 913 605 400",
        "official_website": "https://www.circulobellasartes.com",
        "source": "https://www.circulobellasartes.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Matadero Madrid",
        "place_slug": "matadero_madrid",
        "category": "Centro Cultural / Arte / Diseño",
        "description": "Antiguo matadero municipal (1925) reconvertido en el mayor centro de creación contemporánea de Madrid. 165.000 m² dedicados al arte, diseño, teatro, música y pensamiento. Programación gratuita o muy económica: exposiciones, festivales, mercados, cine al aire libre en verano. Espacio enorme y poco masificado. En el barrio de Arganzuela, a orillas del río Manzanares, junto al Madrid Río (parque fluvial con carril bici y zonas de baño). Ambiente alternativo y creativo muy alejado del circuito turístico habitual.",
        "opening_hours": "Mar-dom: 11-21h (varía por espacio y actividad)",
        "closed_days": "Lunes",
        "price": "Gratuito (mayoría actividades) / Algunos espectáculos desde €5",
        "currency": "EUR",
        "address": "Plaza de Legazpi 8, Arganzuela, Madrid",
        "contact": "mataderomadrid.org | Tel: +34 914 702 401",
        "official_website": "https://www.mataderomadrid.org",
        "source": "https://www.mataderomadrid.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },

    # ── FÚTBOL ────────────────────────────────────────────────────────────────
    {
        "name": "Estadio Santiago Bernabéu — Real Madrid",
        "place_slug": "bernabeu_madrid",
        "category": "Estadio / Fútbol / Turismo Deportivo",
        "description": "El estadio más famoso del mundo junto al Camp Nou. Casa del Real Madrid (14 Champions League). Aforo: 81.044 personas. Tras la renovación 2023 tiene una cubierta retráctil única y pantallas de 360°. Tour del estadio (sin partido): vestuarios, campo, palco presidencial, museo de trofeos con todas las Champions. En días de partido, la atmósfera en los alrededores ya vale el viaje. Ubicado en Paseo de la Castellana, el eje central de Madrid.",
        "opening_hours": "Tour: todos los días 9:30-19h (último acceso) | Partidos: ver calendar realmadrid.com",
        "closed_days": "Días de partido (tour no disponible)",
        "price": "Tour: €25 adultos / €18 reducida - ver realmadrid.com | Entradas partidos: desde €30 a €500 (reventa) - ver realmadrid.com",
        "currency": "EUR",
        "address": "Av. de Concha Espina 1, Chamartín, Madrid",
        "contact": "realmadrid.com | Tel: +34 913 984 300",
        "official_website": "https://www.realmadrid.com",
        "source": "https://www.realmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },
    {
        "name": "Estadio Metropolitano — Atlético de Madrid",
        "place_slug": "metropolitano_madrid",
        "category": "Estadio / Fútbol / Arquitectura Moderna",
        "description": "El estadio más moderno de España (2017). Casa del Atlético de Madrid. Aforo: 68.456 personas. Diseño circular vanguardista con cubierta que crea una acústica brutal. La afición del Atleti es la más apasionada de Madrid y el ambiente en el Metropolitano los días de partido es electrizante. Tour disponible con museo del club. A 20 min del centro en metro (línea 7, San Blas o Las Musas). Sede de la final de Champions League 2019.",
        "opening_hours": "Tour: lun-sáb 10-19:30h, dom 10-15h | Partidos: ver atleticodemadrid.com",
        "closed_days": "Días de partido (solo acceso con entrada)",
        "price": "Tour: €15 adultos / €10 reducida | Entradas partidos: desde €20 - ver atleticodemadrid.com",
        "currency": "EUR",
        "address": "Av. Luis Aragonés 4, San Blas-Canillejas, Madrid",
        "contact": "atleticodemadrid.com | Tel: +34 914 367 064",
        "official_website": "https://www.atleticodemadrid.com",
        "source": "https://www.atleticodemadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 1,
    },

    # ── PARQUES / NATURALEZA ──────────────────────────────────────────────────
    {
        "name": "Real Jardín Botánico de Madrid",
        "place_slug": "botanico_madrid",
        "category": "Jardín Botánico / Naturaleza / Ciencia",
        "description": "Fundado en 1755 por Fernando VI. 8 hectáreas con más de 5.000 especies de plantas de todo el mundo. Terrazas escalonadas en estilo neoclásico. El jardín más antiguo de España y uno de los más importantes de Europa. A 2 min del Prado — visita combinada recomendada. En otoño e invierno tiene menos visitantes y más tranquilidad. El invernadero con plantas tropicales y carnívoras es fascinante.",
        "opening_hours": "Todos los días: 10h-dusk (varía por estación: 18h en invierno, 21h en verano)",
        "closed_days": "1 enero, 25 diciembre",
        "price": "€6 adultos / €3 jubilados / Gratuito menores 10 años - ver rjb.csic.es",
        "currency": "EUR",
        "address": "Plaza de Murillo 2, Retiro, Madrid",
        "contact": "rjb.csic.es | Tel: +34 914 203 017",
        "official_website": "https://www.rjb.csic.es",
        "source": "https://www.rjb.csic.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Casa de Campo y Madrid Río",
        "place_slug": "casa_campo_madrid",
        "category": "Parque Natural / Deporte / Ocio Familiar",
        "description": "El parque más grande de Madrid (1.722 hectáreas — 30 veces el Retiro), antiguo bosque de caza de los Reyes de España. Lago artificial con alquiler de barcas y kayaks. Teleférico (el único de una capital europea) desde la estación de Rosales hasta el corazón del parque, con vistas impresionantes de Madrid. Zoo Aquarium de Madrid. Parque de atracciones. El Madrid Río (11 km de parque lineal a orillas del Manzanares) conecta con la Casa de Campo y tiene playas urbanas en verano.",
        "opening_hours": "Parque: siempre | Teleférico: mar-dom 12-21h (verano) / sáb-dom 12-18h (invierno) | Zoo: 10:30-20h",
        "closed_days": "Teleférico: lunes",
        "price": "Parque: Gratuito | Teleférico: €5,80 adultos / €4,30 niños | Zoo: €26,90 adultos - ver zoo.es",
        "currency": "EUR",
        "address": "Paseo de la Virgen del Puerto s/n, Casa de Campo, Madrid",
        "contact": "esmadrid.com | zoo.es",
        "official_website": "https://www.esmadrid.com/informacion-turistica/casa-de-campo",
        "source": "https://www.esmadrid.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 0, "target_audience": "todos",
        "has_own_agenda": 0,
    },

    # ── OTROS IMPRESCINDIBLES ─────────────────────────────────────────────────
    {
        "name": "Catedral de la Almudena",
        "place_slug": "almudena_madrid",
        "category": "Catedral / Patrimonio / Arquitectura",
        "description": "La catedral de Madrid, construida durante 110 años (1879-1993) — la única catedral del mundo inaugurada por un papa en el siglo XX (Juan Pablo II la consagró en 1993). Mezcla de estilos: neogótico exterior, neorrománico e interior moderno. La cripta (siglo XIX) es más antigua e impresionante. El museo de la catedral tiene acceso a la cubierta con vistas de 360° incluyendo el Palacio Real (que está literalmente al lado). Entrada a la catedral gratuita.",
        "opening_hours": "Catedral: lun-sáb 9-21h, dom 10-21h | Museo/cubierta: lun-sáb 10-14:30h",
        "closed_days": "Variable por actos religiosos",
        "price": "Catedral: Gratuita | Museo y cubierta: €6 adultos / €4 reducida",
        "currency": "EUR",
        "address": "Calle de Bailén 10, Palacio, Madrid",
        "contact": "catedraldelaalmudena.es | Tel: +34 915 422 200",
        "official_website": "https://www.catedraldelaalmudena.es",
        "source": "https://www.catedraldelaalmudena.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Museo Arqueológico Nacional (MAN)",
        "place_slug": "man_madrid",
        "category": "Museo / Arqueología / Historia de España",
        "description": "La historia de España desde la Prehistoria hasta el siglo XIX en un solo edificio. Piezas únicas: la Dama de Elche (busto ibérico del siglo IV a.C., símbolo del museo), la Dama de Baza, el Tesoro de Guarrazar (joyería visigoda), mosaicos romanos, colecciones griegas y egipcias. El edificio (1895) comparte bloque con la Biblioteca Nacional. Gratuito domingos y sábados tardes.",
        "opening_hours": "Mar-sáb: 9:30-20h | Dom y festivos: 9:30-15h",
        "closed_days": "Lunes, 1 enero, 1 mayo, 25 diciembre",
        "price": "€3 adultos / Gratuito domingos y sáb 14-20h - ver man.es",
        "currency": "EUR",
        "address": "Calle Serrano 13, Salamanca, Madrid",
        "contact": "man.es | Tel: +34 915 777 912",
        "official_website": "https://www.man.es",
        "source": "https://www.man.es",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 0,
    },
    {
        "name": "Caixa Forum Madrid",
        "place_slug": "caixaforum_madrid",
        "category": "Centro Cultural / Arte / Arquitectura",
        "description": "Centro cultural de la Fundación La Caixa en un edificio extraordinario: una central eléctrica de 1899 completamente transformada por los arquitectos Herzog & de Meuron (los mismos del Tate Modern de Londres). La fachada de jardín vertical (20 metros de plantas trepadoras) es única en Madrid. Exposiciones temporales de primer nivel (frecuentemente del Louvre, Guggenheim o grandes colecciones internacionales). Enfrente del Prado — perfecta visita complementaria.",
        "opening_hours": "Todos los días: 10-20h",
        "closed_days": "Ninguno",
        "price": "€6 adultos / Gratuito menores 16 años - ver caixaforum.org/madrid",
        "currency": "EUR",
        "address": "Paseo del Prado 36, Retiro, Madrid",
        "contact": "caixaforum.org/madrid | Tel: +34 913 307 300",
        "official_website": "https://caixaforum.org/madrid",
        "source": "https://caixaforum.org/madrid",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0, "is_indoor": 1, "target_audience": "todos",
        "has_own_agenda": 1,
    },
]


def import_static_places_madrid():
    print(f"\nImportando {len(PLACES)} lugares estáticos de Madrid...")
    init_db()
    city_id = get_or_create_city("Madrid", "España")

    for place in PLACES:
        insert_place(city_id, place)

    print(f"\nImportacion completada: {len(PLACES)} lugares de Madrid")


if __name__ == "__main__":
    import_static_places_madrid()
