"""
Importador de lugares estáticos de Buenos Aires.
Cubre venues sin API pública de eventos pero imprescindibles para el turista:
- Usina del Arte
- Centro Cultural Recoleta
- Ecoparque (ex Zoo)
- Casa Rosada
- Cementerio de la Recoleta
- Feria de San Telmo
- Puerto Madero / Costanera Sur
- Caminito (La Boca)
- Tango venues icónicos
- Tecnópolis (cuando esté operativo)
- Luna Park (cerrado temporalmente)
"""
import sys, os
from datetime import date
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from db.database import init_db, get_or_create_city, insert_place

SOURCE_GCBA = "https://www.buenosaires.gob.ar"
TODAY = date.today().isoformat()

PLACES = [
    # ── CENTROS CULTURALES ────────────────────────────────────────────────────
    {
        "name": "Usina del Arte",
        "category": "Centro Cultural / Música",
        "description": "Centro cultural del GCBA en el barrio de La Boca. Sede de conciertos de la Orquesta Filarmónica de Buenos Aires, eventos de jazz, folklore, tango y actividades gratuitas para toda la familia.",
        "opening_hours": "Mar a dom: 14 a 21 h. Eventos según programación.",
        "closed_days": "Lunes",
        "price": "Gratuito (mayoría de eventos) / Con cargo para algunos espectáculos",
        "currency": "ARS",
        "address": "Agustín R. Caffarena 1, La Boca, Buenos Aires",
        "contact": "instagram.com/usinadelarte | buenosaires.gob.ar/cultura/usina-del-arte",
        "official_website": "https://buenosaires.gob.ar/cultura/usina-del-arte",
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": None,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
        "place_slug": "usina_del_arte",
    },
    {
        "name": "Centro Cultural Recoleta (CCR)",
        "category": "Centro Cultural / Arte Contemporáneo",
        "description": "Uno de los centros culturales más importantes de Buenos Aires. Exposiciones de arte, teatro, música, cine y eventos gratuitos en el histórico edificio del Asilo de Pobres (1732), frente al Cementerio de Recoleta.",
        "opening_hours": "Mar a vie: 14 a 21 h | Sab, dom y feriados: 11 a 21 h",
        "closed_days": "Lunes",
        "price": "Gratuito (mayoría de actividades)",
        "currency": "ARS",
        "address": "Junín 1930, Recoleta, Buenos Aires",
        "contact": "Tel: +54 11 5288-6500 | centroculturalrecoleta.org",
        "official_website": "https://centroculturalrecoleta.org",
        "source": "https://centroculturalrecoleta.org",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 1,
        "place_slug": "ccr",
    },

    # ── ATRACCIONES NATURALES / PARQUES ──────────────────────────────────────
    {
        "name": "Ecoparque Buenos Aires (ex Zoo)",
        "category": "Parque / Naturaleza",
        "description": "El ex Zoológico de Buenos Aires reconvertido en Ecoparque, con enfoque en conservación y bienestar animal. Hogar de animales rescatados, área botánica y actividades educativas.",
        "opening_hours": "Mar a dom: 10 a 18 h (última entrada 17 h)",
        "closed_days": "Lunes",
        "price": "Desde $5.000 ARS - ver buenosaires.gob.ar/ecoparque",
        "currency": "ARS",
        "address": "Av. Sarmiento 2601, Palermo, Buenos Aires",
        "contact": "ecoparque.buenosaires.gob.ar",
        "official_website": "https://ecoparque.buenosaires.gob.ar",
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "medium",
        "is_free": 0,
        "is_indoor": 0,
        "target_audience": "familia",
        "has_own_agenda": 0,
        "place_slug": "ecoparque_bsas",
    },
    {
        "name": "Reserva Ecológica Costanera Sur",
        "category": "Parque / Naturaleza",
        "description": "Reserva natural urbana de 350 hectáreas a orillas del Río de la Plata. Ideal para caminatas, birdwatching (más de 340 especies de aves) y actividades al aire libre.",
        "opening_hours": "Mar a dom: 8 a 19 h (verano hasta 20 h)",
        "closed_days": "Lunes",
        "price": "Gratuito",
        "currency": "ARS",
        "address": "Av. Tristán Achával Rodríguez 1550, Puerto Madero, Buenos Aires",
        "contact": "buenosaires.gob.ar/espacioverde/reserva-ecologica-costanera-sur",
        "official_website": "https://buenosaires.gob.ar/espacioverde/reserva-ecologica-costanera-sur",
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "reserva_ecologica_costanera_sur",
    },

    # ── HISTORIA / PATRIMONIO ─────────────────────────────────────────────────
    {
        "name": "Casa Rosada",
        "category": "Monumento / Histórico",
        "description": "Sede del Poder Ejecutivo de Argentina. Visitas guiadas gratuitas al interior del palacio presidencial, donde se puede ver el Salón Blanco, el despacho presidencial y la histórica galería.",
        "opening_hours": "Visitas: sab y dom 10 a 18 h | Museo: lun a vie 10 a 18 h",
        "closed_days": "Variable según agenda presidencial",
        "price": "Gratuito",
        "currency": "ARS",
        "address": "Balcarce 50, San Nicolás, Buenos Aires",
        "contact": "museodelacasarosada.gob.ar",
        "official_website": "https://www.casarosada.gob.ar",
        "source": "https://www.casarosada.gob.ar",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "casa_rosada",
    },
    {
        "name": "Cementerio de la Recoleta",
        "category": "Patrimonio / Histórico",
        "description": "Uno de los cementerios más famosos del mundo. Declarado Monumento Histórico Nacional. Aquí descansan Eva Perón, presidentes, escritores y artistas. Arquitectura neoclásica impresionante.",
        "opening_hours": "Todos los días: 7 a 18 h",
        "closed_days": "Abierto todos los días",
        "price": "Gratuito",
        "currency": "ARS",
        "address": "Junín 1760, Recoleta, Buenos Aires",
        "contact": "buenosaires.gob.ar/cementerios/cementerio-de-la-recoleta",
        "official_website": "https://buenosaires.gob.ar/cementerios/cementerio-de-la-recoleta",
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "cementerio_recoleta",
    },
    {
        "name": "El Cabildo de Buenos Aires",
        "category": "Museo / Histórico",
        "description": "Símbolo de la Revolución de Mayo de 1810. Museo con objetos históricos de la época colonial y virreinal. Construcción original del siglo XVIII en la Plaza de Mayo.",
        "opening_hours": "Mar a vie: 10:30 a 17 h | Sab y dom: 11:30 a 18 h",
        "closed_days": "Lunes",
        "price": "Gratuito",
        "currency": "ARS",
        "address": "Bolívar 65, San Nicolás, Buenos Aires",
        "contact": "museos.buenosaires.gob.ar/cabildo",
        "official_website": "https://museos.buenosaires.gob.ar/cabildo",
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "cabildo_bsas",
    },
    {
        "name": "Museo Histórico Nacional",
        "category": "Museo / Histórico",
        "description": "Colección de objetos, documentos y pinturas sobre la historia argentina desde la época colonial hasta el siglo XX. Incluye el sable corvo del General San Martín.",
        "opening_hours": "Mié a dom: 11 a 18 h",
        "closed_days": "Lunes y martes",
        "price": "Gratuito",
        "currency": "ARS",
        "address": "Defensa 1600, San Telmo, Buenos Aires",
        "contact": "museohistoriconacional.gob.ar",
        "official_website": "https://www.museohistoriconacional.gob.ar",
        "source": "https://www.museohistoriconacional.gob.ar",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "museo_historico_nacional",
    },

    # ── BARRIOS ICÓNICOS ──────────────────────────────────────────────────────
    {
        "name": "Caminito (La Boca)",
        "category": "Atracción / Cultural",
        "description": "Calle-museo al aire libre en el barrio de La Boca. Casas de chapa pintadas con colores vibrantes, tango en vivo en la calle, artistas y artesanos locales. Ícono visual de Buenos Aires.",
        "opening_hours": "Todos los días: 10 a 18 h (artistas y shows de tango)",
        "closed_days": "Abierto todos los días",
        "price": "Gratuito (acceso libre) / Shows de tango con propina",
        "currency": "ARS",
        "address": "Del Valle Iberlucea y Ministro Brin, La Boca, Buenos Aires",
        "contact": "buenosaires.gob.ar/laciudad/caminito",
        "official_website": "https://buenosaires.gob.ar/laciudad/caminito",
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "caminito",
    },
    {
        "name": "Feria de San Pedro Telmo (Feria de San Telmo)",
        "category": "Feria / Mercado",
        "description": "La feria de antigüedades más famosa de Buenos Aires. Cada domingo en la Plaza Dorrego y calles aledañas. Antigüedades, artesanías, libros, ropa vintage, shows de tango en la calle y gastronomía.",
        "opening_hours": "Domingos: 10 a 17 h",
        "closed_days": "Solo funciona los domingos",
        "price": "Gratuito (acceso libre)",
        "currency": "ARS",
        "address": "Plaza Dorrego, Humberto Primo 400, San Telmo, Buenos Aires",
        "contact": "buenosaires.gob.ar/laciudad/feria-de-san-pedro-telmo",
        "official_website": "https://buenosaires.gob.ar/laciudad/feria-de-san-pedro-telmo",
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "feria_san_telmo",
    },
    {
        "name": "Puerto Madero",
        "category": "Barrio / Gastronomía",
        "description": "El barrio más moderno de Buenos Aires. Antiguas dársenas portuarias reconvertidas en restaurantes, bares y paseos. Incluye la Costanera Sur, el Puente de la Mujer (Calatrava) y la Reserva Ecológica.",
        "opening_hours": "Siempre accesible",
        "closed_days": "Ninguno",
        "price": "Gratuito (acceso público)",
        "currency": "ARS",
        "address": "Puerto Madero, Buenos Aires",
        "contact": "buenosaires.gob.ar",
        "official_website": SOURCE_GCBA,
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "puerto_madero",
    },
    {
        "name": "Palermo Soho y Hollywood",
        "category": "Barrio / Gastronomía / Moda",
        "description": "Los barrios de moda de Buenos Aires. Bares, restaurantes, tiendas de diseñadores locales, galerías de arte y vida nocturna activa. El corazón del Buenos Aires cosmopolita.",
        "opening_hours": "Comercios: 10 a 21 h | Restaurantes y bares hasta la madrugada",
        "closed_days": "Variable según local",
        "price": "Gratuito (acceso público)",
        "currency": "ARS",
        "address": "Palermo Soho: Thames y Honduras | Palermo Hollywood: Juan B. Justo y Santa Fe, Buenos Aires",
        "contact": "buenosaires.gob.ar",
        "official_website": SOURCE_GCBA,
        "source": SOURCE_GCBA,
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "jovenes",
        "has_own_agenda": 0,
        "place_slug": "palermo_soho",
    },

    # ── TANGO (IDIOSINCRASIA ARGENTINA) ──────────────────────────────────────
    {
        "name": "Esquina Homero Manzi",
        "category": "Tango / Espectáculo",
        "description": "Uno de los más famosos espectáculos de tango de Buenos Aires. Show con cena opcional en el histórico edificio de la esquina de San Juan y Boedo, inspirador de tangos clásicos.",
        "opening_hours": "Shows: lunes a sábado 22 h. Cena desde 21 h.",
        "closed_days": "Domingos",
        "price": "Desde USD 80 (show) / USD 120 (show + cena) - ver esquinahomeromanzi.com.ar",
        "currency": "USD",
        "address": "San Juan 3601, Esquina Boedo, Buenos Aires",
        "contact": "esquinahomeromanzi.com.ar | Tel: +54 11 4957-8488",
        "official_website": "https://www.esquinahomeromanzi.com.ar",
        "source": "https://www.esquinahomeromanzi.com.ar",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "adultos",
        "has_own_agenda": 0,
        "place_slug": "esquina_homero_manzi",
    },
    {
        "name": "El Viejo Almacén",
        "category": "Tango / Espectáculo",
        "description": "Histórico escenario de tango en San Telmo (desde 1969). Show de tango con orquesta en vivo y cena opcional. Uno de los más tradicionales de Buenos Aires.",
        "opening_hours": "Shows: todos los días 22 h. Cena desde 21 h.",
        "closed_days": "Ninguno",
        "price": "Desde USD 75 (show) / USD 115 (show + cena) - ver viejoalmacen.com",
        "currency": "USD",
        "address": "Independencia 300, San Telmo, Buenos Aires",
        "contact": "viejoalmacen.com | Tel: +54 11 4307-7388",
        "official_website": "https://www.viejoalmacen.com",
        "source": "https://www.viejoalmacen.com",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "adultos",
        "has_own_agenda": 0,
        "place_slug": "el_viejo_almacen",
    },
    {
        "name": "Milonga La Catedral",
        "category": "Tango / Milonga",
        "description": "La milonga más bohemia y auténtica de Buenos Aires. En un espacio artístico de tres pisos en Almagro. Clases de tango, milonga hasta la madrugada, ambiente underground.",
        "opening_hours": "Mié a dom: clases 21 h / Milonga desde 23 h hasta las 4-5 h",
        "closed_days": "Lunes y martes",
        "price": "Desde $5.000 ARS (entrada) + consumición",
        "currency": "ARS",
        "address": "Sarmiento 4006, Almagro, Buenos Aires",
        "contact": "instagram.com/lacatedralclub",
        "official_website": "https://www.instagram.com/lacatedralclub",
        "source": "https://www.instagram.com/lacatedralclub",
        "last_verified": TODAY,
        "confidence_level": "medium",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "adultos",
        "has_own_agenda": 0,
        "place_slug": "milonga_la_catedral",
    },

    # ── TEMPORALMENTE CERRADOS / EN RENOVACIÓN ────────────────────────────────
    {
        "name": "Luna Park Stadium",
        "category": "Estadio / Espectáculos",
        "description": "Histórico estadio cubierto de Buenos Aires (capacidad 8.000). Sede de boxeo, conciertos y espectáculos desde 1932. Actualmente cerrado para renovación completa. Reapertura prevista próximamente.",
        "opening_hours": "CERRADO - En proceso de renovación",
        "closed_days": "Cerrado temporalmente",
        "price": "Ver lunapark.com.ar para actualizaciones",
        "currency": "ARS",
        "address": "Av. Eduardo Madero 420, Buenos Aires",
        "contact": "lunapark.com.ar",
        "official_website": "https://www.lunapark.com.ar",
        "source": "https://www.lunapark.com.ar",
        "last_verified": TODAY,
        "confidence_level": "high",
        "is_free": 0,
        "is_indoor": 1,
        "target_audience": "todo publico",
        "has_own_agenda": 0,
        "place_slug": "luna_park",
    },
    {
        "name": "Tecnópolis",
        "category": "Parque / Ciencia y Tecnología",
        "description": "El parque de ciencia, tecnología y arte más grande de Latinoamérica. Exposiciones interactivas, shows al aire libre y actividades gratuitas para toda la familia. Funciona en temporadas.",
        "opening_hours": "Variable según temporada - verificar en tecnopolis.ar",
        "closed_days": "Fuera de temporada",
        "price": "Gratuito en temporada",
        "currency": "ARS",
        "address": "Av. General Paz y Av. Dr. Beiró, Villa Martelli, Buenos Aires",
        "contact": "tecnopolis.ar",
        "official_website": "https://www.tecnopolis.ar",
        "source": "https://www.tecnopolis.ar",
        "last_verified": TODAY,
        "confidence_level": "medium",
        "is_free": 1,
        "is_indoor": 0,
        "target_audience": "familia",
        "has_own_agenda": 0,
        "place_slug": "tecnopolis",
    },
]


def import_static_places_bsas():
    print(f"\nImportando {len(PLACES)} lugares estáticos de Buenos Aires...")
    init_db()
    city_id = get_or_create_city("Buenos Aires", "Argentina")

    imported = 0
    for place in PLACES:
        insert_place(city_id, place)
        imported += 1

    print(f"\nImportacion completada: {imported} lugares estaticos de Buenos Aires")


if __name__ == "__main__":
    import_static_places_bsas()
